### PR TITLE
LPS-161876 Add lang-sanitizer tool support

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Manually forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/127312

**Pull request closed without merging**
