### PR TITLE
LPS-122967 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
Resent: https://github.com/petershin/liferay-portal/pull/1286

**Comment by petershin** [comment]
ci:stop

**Pull request closed without merging**
