### PR TITLE
LRQA-65525 Use latest project-templates

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
hey @gamerson, I need to bump up project templates workspace to use bnd 5.2.0.

The xml diff between maven (using bnd 5.2.0) and workspace bnd (4.3.0) is an alphabetical sorting in that portlet.xml. bnd 5.2.0 sorts, while 4.3.0 doesnt

https://github.com/petershin/liferay-portal/pull/1373/commits/c8d59f6421baa65290a58e47646fcdaa1f8b194b

We should consider bumping bnd in gradle-plugins/workspace itself.

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Pull request closed without merging**
