### PR TITLE
LPS-100168 Set default package manager

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
@david-truong - This pull sets the default package manager to `npm`.  Are there any changes needed in `gradle-plugins-workspace`?

**Comment by david-truong** [comment]
There's probably some duplicate logic we could remove from gradle-plugins-workspace.

**Comment by petershin** [comment]
@david-truong - Ok, I'll send this pull to bchan

**Comment by petershin** [comment]
ci:forward

**Pull request closed without merging**
