### PR TITLE
lps-83463

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by petershin** [comment]
Some additional comments:

The `if` check below seems like it can be removed.

https://github.com/lawrence-lee/liferay-portal/blob/master/modules/sdk/project-templates/project-templates-theme-contributor/src/main/resources/archetype-resources/build.gradle#L14-L16

Please check `L17-L31`. These lines can be grouped together using the new pattern.

https://github.com/lawrence-lee/liferay-portal/blob/master/modules/sdk/project-templates/project-templates-theme/src/main/resources/archetype-resources/pom.xml#L17-L31

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
@petershin fixed! 

All except ```The if check below seems like it can be removed.

https://github.com/lawrence-lee/liferay-portal/blob/master/modules/sdk/project-templates/project-templates-theme-contributor/src/main/resources/archetype-resources/build.gradle#L14-L16```

I just tested this, but there's some transitive dependencies that need that repositories block. 

Here's the error i got
```* What went wrong:
Could not resolve all dependencies for configuration ':portalCommonCSS'.
> Cannot resolve external dependency com.liferay:com.liferay.frontend.css.common:2.0.0 because no repositories are defined.
  Required by:```

**Comment by petershin** [comment]
@lawrence-lee - Yes, the `repositories` closure is needed.  I meant deleting `L14-16` should be ok since the `if` check mirrors the check on `L1`.  Updated code is below:

```gradle
#if (${projectType} != "workspace")buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins", version: "@com.liferay.gradle.plugins.version@"
	}

	repositories {
		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.plugin"

repositories {
	maven {
		url "https://repository-cdn.liferay.com/nexus/content/groups/public"
	}
}#end
```

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/62226

**Pull request closed without merging**
