### PR TITLE
LPS-105747 changelogs

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Peter,

Please see one of the differences(some commits are missing):

Before my changes:
https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-util/CHANGELOG.markdown#commits
After my changes:
https://github.com/petershin/liferay-portal/blob/bbd94c922791d6cbcfebfe797a4afcf9d10d54b3/modules/sdk/gradle-util/CHANGELOG.markdown#commits

----------------------

[XYZ]
[XYZ]: http://google.com/

I think "[XYZ]" is referring some link, and "[XYZ]: " is the definition of that link.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/86626

**Pull request closed without merging**
