### PR TITLE
LPS-99577 deployFast task

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
gradle plugins tests passed here: https://github.com/gamerson/liferay-portal/pull/329#issuecomment-523525604

**Comment by petershin** [comment]
@gamerson - this looks good. I'm thinking over one change and will follow up with you

**Comment by petershin** [comment]
To reduce configuration times the `deployFast` task is added to just `OSGi` projects and the child tasks were merged into the `deployFast` task

**Comment by petershin** [comment]
Sent to Brian:

https://github.com/brianchandotcom/liferay-portal/pull/77350
https://github.com/brianchandotcom/liferay-portal/pull/77351

**Pull request closed without merging**
