### PR TITLE
LPS-160184 LPS-160184 JSP bnd plugin should not add Imports for Classes

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
@petershin I rebased master and this pull has been passed ci:gradle-plugins:test and ci:statable test. The SF test failed, but its not related to our code.

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
@simonjhy - Please sort: `java.util.Map` goes before `java.util.logging` bc of capitalization. In `imports_without_multipackages_and_statics.jsp`, `java.util.logging.Logger.*` is listed twice. Remove the second one if its not needed.

The #ci team modified ci:test:relevant to skip running when only files in the `sdk` directory are touched to help speed things up

Since this pull touches projects outside of the `sdk` directory (ie portal-osgi-web-wab-generator-impl), the ci:test:relevant suite will be run. Run that test suite on your branch and confirm w the #ci channel that the errors are not related. I'll need to post a link to the slack message on the pull that's sent to bchan

**Comment by simonjhy** [comment]
@petershin ok thanks peter.

**Pull request closed without merging**
