### PR TITLE
POSHI-344 Add geckodriver support to poshi runner gradle plugin

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-344

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by petershin** [comment]
@kenjiheigel - The `private boolean _downloadWebDriverBrowserBinary;` seems out of place, I wouldn't have expected that logic in the `populate` method. I think the easiest fix is to remove the `POSHI-344 Simplify` as long as it doesn't break any existing functionality

**Comment by kenjiheigel** [comment]
Discussed further with Peter over Slack and will rework and resend.

**Comment by kenjiheigel** [comment]
Resent: 
https://github.com/petershin/liferay-portal/pull/1663

**Pull request closed without merging**
