### PR TITLE
LPS-152789

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
Rebased to fix conflict errors: https://github.com/petershin/liferay-portal/pull/1655

**Pull request closed without merging**
