### PR TITLE
LPS-97550 testIntegration classes support

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@gamerson - Can we follow the pattern in [gradle-plugins-service-builder/src/gradleTest/smoke/build.gradle#L39-L41](https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins-service-builder/src/gradleTest/smoke/build.gradle#L39-L41) to avoid checking in all the generated files?

If we can go with that new pattern, please copy the content in that `service.xml` as much as possible too.

```
<service-builder package-path="com.example.sample">
	<namespace>Sample</namespace>
	<entity local-service="true" name="Foo" remote-service="true" uuid="true">

	...
</service-builder>
```

**Comment by gamerson** [comment]
resent here: https://github.com/petershin/liferay-portal/pull/604

**Pull request closed without merging**
