### PR TITLE
LPS-96590 IDE profile support

### PR DESCRIPTION
**Pull request by gamerson**
hey @petershin  here is a refactored approach that splits everything out into separate Settings plugin that is activated by a property -Dide.profile= .

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
so the way this works is, when you want to setup a profile, you do
1. `cd modules/apps/portal-search`
2. `gw -Dide-profile=search setIdeProfile`
3. in Eclipse or Inteliij you do standard gradle project import and in the Gradle VM args you pass `-Dide-profile=search`

And now Eclipse or Intellij will just import the 100 or so portal-search and related dependent projects.  and they will be full gradle projects so you can run gradle tasks, etc.  And if you want to specify multiple profiles (you run setIdeProfile from multiple locations) you can just modify the last step and add `-Dide-profile=search,workflow,sdk`

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
Closing based on latest discussion with Greg.

**Pull request closed without merging**
