### PR TITLE
LPS-159582 Add bundle url property back for 7.3 and 7.4 maven workspace

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
Hi Peter, the tests are passed here https://github.com/Seiphon/liferay-portal/pull/35

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:forward

**Pull request closed without merging**
