### PR TITLE
LPS-159640 upgrade gradle to 6.9.2  @simonjhy

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
@petershin here is test result https://github.com/simonjhy/liferay-portal/pull/90

**Comment by petershin** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by petershin** [comment]
@simonjhy - For rebase errors, I always create a new pull - it's easier for other people to see which files have changed.

Rebased this pull w the latest: https://github.com/petershin/liferay-portal/pull/1836

**Pull request closed without merging**
