### PR TITLE
LPS-100078 Semver project-templates

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
@petershin  Please ask Brian to publish `project templates`

**Comment by gamerson** [comment]
hey @petershin   the project-template tests are passing everything except what is already failing on master.

**Comment by petershin** [comment]
@gamerson - Can you send a separate pull to fix the test?

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/77752

**Pull request closed without merging**
