### PR TITLE
LPS-154070 create all docker file for environments

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
https://github.com/petershin/liferay-portal/pull/1687

@simonjhy - I saw this test fail on other pulls. Do you know what's causing these failures?

**Pull request closed without merging**
