### PR TITLE
LPS-148304 Fix gradleTest issues

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @petershin , gradeTest is passed hre https://github.com/Seiphon/liferay-portal/pull/69

It seems "apply plugin" is a legacy way to declare gradle plguin, do we need to replace them all with "plugins { }"？

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:norebase:gradle-plugins

**Comment by Seiphon** [comment]
ci:test:norebase:project-templates

**Comment by petershin** [comment]
@Seiphon - This looks like a CI specific issue. I'm following up w the CI team to confirm

**Comment by petershin** [comment]
Continued testing here: https://github.com/petershin/liferay-portal/pull/1974

**Pull request closed without merging**
