### PR TITLE
LPS-92634 Update operation ids

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
I'm feeling lucky

**Comment by petershin** [comment]
ci:test:forward

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:forward

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by jotascript** [comment]
Just started reviewing :)

**Pull request closed without merging**
