### PR TITLE
LPS-125623 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-125623

@petershin can you please review, especially the last commit? I ran `git grep										"fiftyonedegrees"` to find all references, but maybe there's some other command that needs to be run to ensure full removal? CII will remove in build-test, build-test-batch, etc. Thank you!

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
Test failures seem unrelated. Please let me know when you're done with your review :). I'm happy to rebase and retest if you don't have any changes.

**Comment by petershin** [comment]
@jpince - It looks like CI is running more tests b/c of all the changes in bchan's origin.  Rerunning the tests against upstream: https://github.com/petershin/liferay-portal/pull/1336

**Comment by petershin** [comment]
@jpince - It looks ok to me.  If the CI tests pass, will forward to bchan

**Comment by jpince** [comment]
@petershin thank you!

**Pull request closed without merging**
