### PR TITLE
LPS-110131

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@pyoo47 - Do you know why the previous `CI` job failed?

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by pyoo47** [comment]
@petershin Sorry, we had a few bad Jenkins slaves slip through our verification logic. The problem with our verification logic has been corrected. https://liferay.slack.com/archives/C19PWQ74J/p1584571816073400

**Pull request closed without merging**
