### PR TITLE
LPS-159736 Add docker documentation

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Manually forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/121888

**Pull request closed without merging**
