### PR TITLE
LPS-110781 Enable incremental build for the baseline task

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
@pyoo47 - This failure looks unrelated.  Will the CI or QA team manually forward this pull to Brian?

**Comment by pyoo47** [comment]
@petershin Enforcement of the rule to limit who can send pulls directly to BChan has not yet started. You should be able to send it yourself. We are anticipating starting enforcement sometime this morning.

**Comment by petershin** [comment]
@pyoo47 - ok, sent to brian: https://github.com/brianchandotcom/liferay-portal/pull/86759

**Pull request closed without merging**
