### PR TITLE
LPS-95688 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by christopherbryanboyd**
@gamerson @lawrence-lee

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
hey @petershin  the test:gradle-plugins will likely fail here until bchan merges my changes ont he other pull.  

The reason the gradle-plugins tests are failing is that it appears some upstream BOMs changed slightly, it was nothing to do with change sto the plugins

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/73992

Ran the tests here: https://github.com/petershin/liferay-portal/pull/530

**Pull request closed without merging**
