### PR TITLE
LPS-97550 fix problematic tests

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
Something weird is going on with these tests.

**Comment by petershin** [comment]
Kicked off a new test here: https://github.com/petershin/liferay-portal/pull/564

**Comment by petershin** [comment]
Continued on https://github.com/petershin/liferay-portal/pull/568

**Pull request closed without merging**
