### PR TITLE
LPS-174878 Add javax.annotation-api in release.api jar

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @petershin, the relevant test and stable test have been passed here https://github.com/Seiphon/liferay-portal/pull/64 , but there are some sf issue which is not related to my code.

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Manually sent to bchan: https://github.com/brianchandotcom/liferay-portal/pull/130287

**Pull request closed without merging**
