### PR TITLE
LPS-85946 use latest

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
hey @petershin   Can you ask Brian to publish `gradle-plugins-target-platform`  ? Thanks!

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/63949

**Pull request closed without merging**
