### PR TITLE
LPS-105747 Changelogs

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Peter,

**Change 1:** Use git log twice to build changelogs.

First time: for commits section
Second time: for dependencies section

-----------------------------

**Change2:** Fix regex to get ticket number and commit message.

Because we have a lot of style in commit messages.
For example:

1. 

_One space between ticket numbers:_
```
LPS-105304 LPS-105231 prep next
```

2. 

_"/" between ticket numbers:_

```
LPS-105237/LPS-105290 Fix changelogs
```

3. 

_space +_ "|" _+ space between ticket numbers:_

```
LPS-104318 | LPS-104854
```

4. 

Starts with "m"
```
mLPS-74544 prep next
```

5. 

Starts with " "

```
  LPS-74544 prep next
```

6. 

Starts with "Revert"
```
  Revert "LPS-82828 Deprecated as of 7.1.0"
```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
cc @hhuijser

**Comment by ling-alan-huang** [comment]
@petershin, @hhuijser, BTW, I will take one day PTO for Jan.16 Thursday.

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/83228

**Pull request closed without merging**
