### PR TITLE
LPS-167335 fix gradleTest error for gradle workspace plugin

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
@petershin here is test result https://github.com/simonjhy/liferay-portal/pull/93.

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:stable

**Comment by petershin** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by petershin** [comment]
ci:test:relevant:norecompile

**Comment by petershin** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:forward

**Comment by petershin** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
@simonjhy - Partial forward: https://github.com/petershin/liferay-portal/pull/1843

Please send the other changes in a separate pull if needed

**Comment by petershin** [comment]
ci:stop

**Pull request closed without merging**
