### PR TITLE
LPS-102342 Make liferay-npm-scripts builds output to build/node/packageRunBuild/resources

### PR DESCRIPTION
**Pull request by wincent**
See: https://issues.liferay.com/browse/LPS-102342

And: https://github.com/liferay/liferay-npm-tools/issues/272

For more context.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
cc @jbalsas

**Comment by petershin** [comment]
@wincent - I switched `packageRunBuild` to run before the `processResources` task to break the circular dependency. now the `processResources` task just copies the results from `packageRunBuild`

during testing, I was confused by why the `processResources` task always ran and realized that the `replaceSoyTranslation` task wasn't disabled yet

would it be possible to add https://github.com/liferay/liferay-npm-tools/issues/277 to `liferay-portal` master first?

**Comment by wincent** [comment]
@petershin:

- Rebased this on latest master.
- Updated (to the even newer version of) liferay-npm-scripts, which does the work formerly done by `replaceSoyTranslation`.
- Turned off `replaceSoyTranslation` in the three places that it was formely turned on.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
I didn't close this; no idea what's up.

**Comment by petershin** [comment]
Added changes here: https://github.com/petershin/liferay-portal/pull/724

**Pull request closed without merging**
