### PR TITLE
LPS-94948 Apply it (specifically did not change the smoketest usages)

### PR DESCRIPTION
**Pull request by rotty3000**
/cc @gamerson @david-truong

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:norebase

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
Sent to Ray: https://github.com/rotty3000/liferay-portal/pull/1423

**Pull request closed without merging**
