### PR TITLE
[Community Contribution] LPS-96247

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-96247

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:test:gradle-plugins

**Comment by jrodbx** [comment]
Does this need to be rebased on latest master to pick up this fix: https://github.com/liferay/liferay-portal/commit/446a7995e74512811226daef127d54c3eb567024?

**Comment by jrodbx** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
The changes need to be published to the `.m2-tmp` directory for the continiuous integration tests.  Sent those changes here: https://github.com/petershin/liferay-portal/pull/546

**Comment by petershin** [comment]
ci:stop

**Pull request closed without merging**
