### PR TITLE
 LPS-77897

### PR DESCRIPTION
**Pull request by petershin**
@david-truong

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by david-truong** [comment]
@petershin i tried to add the expectFailure tag for CI so that even if the tests fail it will still pass the build.  But if CI fails because it prints the word failure this won't work because this test will still run and fail.

**Comment by petershin** [comment]
@david-truong - The tests passed.  Have you had a chance to review the failure in https://github.com/petershin/liferay-portal/pull/313#issuecomment-443811275 ?

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/65613

**Pull request closed without merging**
