### PR TITLE
LPS-111291 Gradle 6.6.1

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
@yichenroy - Can the CI team configure one CI server with double the memory for just this pull?

This pull upgrades Gradle to Gradle 6 and CI seems like its running out of memory during `ant all`.

**Comment by yichenroy** [comment]
@petershin okay, I'll consult with the team.

**Comment by yichenroy** [comment]
@petershin this run uses slaves on https://test-1-24.liferay.com where all slaves have 32 GB memory (regular CI slaves  on other masters have only 16 GB each)

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
@yichenroy - Can we make every CI test from this pull use 32 GB of memory?

I'll need to run the CI test multiple times against different CI suites (bundle, stable, relevant, etc)

**Comment by yichenroy** [comment]
@petershin it is possible but the test will need to be manually triggered on Jenkins, it's currently not possible to do this through github comments.

I'll message you on slack.

**Comment by yichenroy** [comment]
@petershin I added a project role for you on test-1-24 so you should be able to start pull request tests on test-1-24, for any future runs you can go to this page:
https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest(master)/464/
1. On the left side, click on `Rebuild`, this will take you to the parameters page pre-filled with the appropriate parameters.
2. Modify the `CI_TEST_SUITE` to the suite you want to run
3. Click on `Rebuild` and the build will start.

**Comment by petershin** [comment]
@yichenroy - I followed the steps and clicked rebuild

**Comment by petershin** [comment]
Rebased w the latest: https://github.com/petershin/liferay-portal/pull/1220

**Pull request closed without merging**
