### PR TITLE
LPS-84273

### PR DESCRIPTION
**Pull request by lawrence-lee**
@petershin can you ask Brian to publish the project templates? This includes the updated `gradle-plugins-workspace`. Thank you\!

### CODE REVIEW

**Comment by lawrence-lee** [comment]
cc @gamerson

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/62019

**Pull request closed without merging**
