### PR TITLE
LPS-111291 Upgrade Gradle

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:stable

**Comment by petershin** [comment]
ci:test:stable

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
I'm feeling lucky

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:test:bundle

**Pull request closed without merging**
