### PR TITLE
LPS-109820 Baseline

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
Hi @john-co, do any of the test failures look related to this pull?

**Comment by petershin** [comment]
Hi @rotty3000, `Gradle 6.x` won't allow overriding tasks.  This pull removes the `BndBuilderPlugin` to avoid adding the `bnd` `baseline` task.  When you have time, please take a look at the changes.

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
The [testray result](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1046219252) is missing a lot of testcases from `ci test`. I'm re-running the tests and reached out to CII.

**Comment by john-co** [comment]
I'm not sure how to easily evaluate gradle-plugins-test-jdk8 tests since it's not run daily so I can't pull up a history. I ran the test in a local PR [here](https://github.com/john-co/liferay-portal/pull/242) as a baseline.

Other than that, test failures in `ci test` are unrelated. :heavy_check_mark: 
**ci test Testray comparison:**
[Unique test failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1045865523&testrayRunIdA=1046219254&statusB=2) - not related
[Common test failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1045865523&testrayRunIdA=1046219254&statusB=3) - not related

**Comment by john-co** [comment]
ci:stop

**Comment by petershin** [comment]
Thank you @john-co!  I can take care of the `gradle-plugins` failure.

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/86117

**Pull request closed without merging**
