### PR TITLE
LPS-87419

### PR DESCRIPTION
**Pull request by lawrence-lee**
Please publish a new `gradle-plugins-workspace`, `portal-tools-bundle-support`, `gradle-plugins`, `gradle-plugins-defaults`, and project templates

@gamerson, I tested the `default format` with tar.gz in `portal-tools-bundle-support` manually, and we can support zips still

### CODE REVIEW

**Comment by petershin** [comment]
@lawrence-lee - Can you update the commits to follow the pattern below?  It'll help speed up the review process for future pulls.  If you see any issues with this approach, we can adjust the pattern.

- All manual changes go first
- `LPS-XXX Update project template tokens` (`build.gradle` `ext.projectTemplateTokens` changes)
- `LPS-XXX Use latest xxx` (auto-generated changes only - `gw installCache updateFileVersions`)
- `LPS-XXX FAKE GRADLE CACHE` (`m2-tmp` jars)

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/65177

**Pull request closed without merging**
