### PR TITLE
LPS-95285 Spring Portlet MVC and PortletMVC4Spring support

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
cc @ngriffin7a

**Comment by gamerson** [comment]
cc @jtydhr88

**Comment by gamerson** [comment]
cc @jtydhr88

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:close

**Pull request closed without merging**
