### PR TITLE
LPS-102342 Updates liferay-npm-scripts to v10.1.2

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Based on the results above 👆:

- Extraneous sourcemaps no longer appear on consecutive invocations of `liferay-npm-scripts build` because they get cleaned up after the changes in https://github.com/liferay/liferay-npm-tools/pull/283
- There's a slight diff in `manifest.json` after a `gradlew clean deploy`. The diff is just positional because the algorithm is parallelized so entries can be processed differently. @izaera, can you confirm this is indeed the case? @petershin, is this acceptable, or do we need to find a way to sort those keys to always have the same output?
- The `npmPackageRunBuild` task does not seem to get skipped... I assume that's the "caching" part we removed from this PR in order to fix this?

I haven't see any other divergences other than the ones listed above, at least on OSX. I'll test on Windows tomorrow.

**Comment by izaera** [comment]
@jbalsas @petershin I can confirm that manifests may have random ordering. But I can sort it alphabetically if needed. Just create an issue in https://github.com/liferay/liferay-js-toolkit/issues if needed :+1:

**Comment by petershin** [comment]
@jbalsas - Updated `liferay-npm-scripts` in `master-private`.  Rerunning the `CI` tests here: https://github.com/petershin/liferay-portal/pull/724

@izaera - That'd be very helpful! It'll allow anyone to identify a problem by doing a simple diff.

**Comment by petershin** [comment]
@izaera - added a ticket: https://github.com/liferay/liferay-js-toolkit/issues/435

**Comment by jbalsas** [comment]
Hey @petershin, pushed an additional commit after making the `manifest.json` generation stable.

I could only observe one difference when you run

```
- git clean -fdx
- gradlew deploy
```

As far as I can tell, the `setup-yarn` is skipped and the `node_modules` folder is not properly set when you run deploy that time, so I'm afraid we can't fully trust that output, since the input is different...

Not sure what would be the best way to fix that.

Thoughts?

**Comment by petershin** [comment]
@jbalsas - Added a temp patch.  See https://github.com/petershin/liferay-portal/pull/724/commits/7223a93918dba46aa11cc7bcde94287a6896290d on the latest https://github.com/petershin/liferay-portal/pull/724.

I'll clean up the fix and force update the branch later today.

**Comment by petershin** [comment]
@jbalsas - running the CI tests with your latest changes: https://github.com/petershin/liferay-portal/pull/724

**Pull request closed without merging**
