### PR TITLE
LPS-112250 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
Tests passed here: https://github.com/petershin/liferay-portal/pull/970#issuecomment-617379479

**Comment by petershin** [comment]
Forwarding to Brian: https://github.com/petershin/liferay-portal/pull/974

**Comment by petershin** [comment]
@lawrence-lee - I kept everything the same this time.  Its better to publish `project-templates-exensions` first and then everything else.

```
LPS-0 Use latest project-templates-exensions
LPS-0 Use latest project-templates archetypes
LPS-0 FAKE GRADLE CACHE
```

**Comment by lawrence-lee** [comment]
Hey @petershin, the reason for failing test wasnt order of publish, but it was just the delay between when `ci` tested it using my fake gradle cache and the version changed/prep next of when `gradle-plugins-workspace` was published

**Pull request closed without merging**
