### PR TITLE
LPS-98190 Workspace Metatype annotations support

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
hey @petershin   The gradle plugin failure was just a network error, everything else looks good to go.

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/76109

**Pull request closed without merging**
