### PR TITLE
LPS-85543 Fix test batch parameter

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
Hey @michaelhashimoto @jpince @petershin,

We're adding a new batch for the pr tester to test the `gradleTests` in `modules/sdk`. This should not run on every pull. Only on pulls that designate `ci:test:gradle-plugins`

**Comment by jpince** [comment]
@lawrence-lee since you have [this line](https://github.com/petershin/liferay-portal/pull/226/files#diff-66d24afc65d5a682dc718d87a8b0adeeR1150) under test.batch.names, it will currently run in upstream acceptance and with ci:test. If you ONLY want it to run when `ci:test:gradle-plugins` is called, you need to remove that line.

**Comment by petershin** [comment]
@lawrence-lee Added the change @jpince suggested

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/63378

**Pull request closed without merging**
