### PR TITLE
LPS-150857

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
See https://github.com/petershin/liferay-portal/pull/1754

**Comment by petershin** [comment]
@marcellustavares - I'm upgrading Gradle to 6.9.2 so the new library can be applied. The pull will likely be sent Friday afternoon (want to avoid blocking the weekly release due to any unexpected regression issues)

**Pull request closed without merging**
