### PR TITLE
LPS-123192 Plugins

### PR DESCRIPTION
**Pull request by petershin**
https://github.com/petershin/liferay-portal-ee/pull/297
https://github.com/petershin/liferay-portal-ee/pull/298
https://github.com/petershin/liferay-portal-ee/pull/299
https://github.com/petershin/liferay-portal-ee/pull/300

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:stable

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Pull request closed without merging**
