### PR TITLE
LPS-143833 Added notifications to mvc-portlet template

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by petershin** [comment]
@simonjhy - there's a lot of unneeded new lines and instances where spaces are used instead of tabs

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
@petershin I checked all archetype source files and found some lines not use tab, I updated them. Can you help to check it ? Thanks.

**Comment by petershin** [comment]
https://github.com/lawrence-lee/liferay-portal/pull/260

**Pull request closed without merging**
