### PR TITLE
LPS-97114 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
hey @petershin  can you ask BChan to publish these templates?  thanks

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/74772

**Pull request closed without merging**
