### PR TITLE
lps-103582

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
If tests pass, please ask Brian to publish `project-templates-*`

**Comment by petershin** [comment]
@lawrence-lee - in future pulls, please run `gw installCache updateFileVersions` on `project-templates-extensions` first and then `project-templates`. See https://github.com/petershin/liferay-portal/pull/764

**Comment by lawrence-lee** [comment]
@petershin, got it. It looks like there are still issues with these NPM angular tests. Can you take out 5d191ee20bd12ab2bd53bbc3edf7f3a3f12bd353? This is the commit that removes the ignores.

**Comment by petershin** [comment]
@lawrence-lee - sure. will remove that and rerun the test

**Comment by petershin** [comment]
Rerunning tests here: https://github.com/petershin/liferay-portal/pull/764

**Pull request closed without merging**
