### PR TITLE
LPS-158124 Seiphon

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
@Seiphon - If [this SF change ](https://github.com/petershin/liferay-portal/pull/1940/commits/70e55ebf9bb4549b94f3b7604b30162de760dd9a#diff-f5057ff1629d734c97f27d5d773ee5851ea78419d64eafd04cf3fa3fb7271f21R29)caused the failure, rewrite it like this:

```
dependsOn "verifyProduct"
dependsOn "createDockerfile"
```

**Comment by Seiphon** [comment]
> @Seiphon - If [this SF change ](https://github.com/petershin/liferay-portal/pull/1940/commits/70e55ebf9bb4549b94f3b7604b30162de760dd9a#diff-f5057ff1629d734c97f27d5d773ee5851ea78419d64eafd04cf3fa3fb7271f21R29)caused the failure, rewrite it like this:
> 
> ```
> dependsOn "verifyProduct"
> dependsOn "createDockerfile"
> ```

OK, I will try it

**Comment by Seiphon** [comment]
ci:test:gradle-plugins

**Comment by Seiphon** [comment]
> > @Seiphon - If [this SF change ](https://github.com/petershin/liferay-portal/pull/1940/commits/70e55ebf9bb4549b94f3b7604b30162de760dd9a#diff-f5057ff1629d734c97f27d5d773ee5851ea78419d64eafd04cf3fa3fb7271f21R29)caused the failure, rewrite it like this:
> > ```
> > dependsOn "verifyProduct"
> > dependsOn "createDockerfile"
> > ```
> 
> OK, I will try it

Hi @petershin , it seems the faluire is not about the dependsOn task order, it also failed after I rewritede it. https://github.com/Seiphon/liferay-portal/pull/67

**Comment by petershin** [comment]
ci:forward

**Pull request closed without merging**
