### PR TITLE
LPS-117975 Remove mergeLang

### PR DESCRIPTION
**Pull request by petershin**
Hi Brian, the mergeLang task is used in a lot of commerce projects and its not cacheable.<br /><br />I'll send pulls to see if all the usages can be safely replaced and then remove the task from the build.

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
@john-co - Is this failure related to the changes in my pull or is it a known issue?

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by john-co** [comment]
The tests are affecting other PRs. Need to disable: LocalFile.CPSitetemplates#AddSiteTemplateApplySiteTemplateChangesToSite
LocalFile.CPSitetemplates#DeleteSiteTemplateAssociatedWithASite

cc/ @Tim-Cao @manoelcyreno

**Comment by petershin** [comment]
@john-co - appreciate the review!  when this happens, what's the right way to forward this to bchan?

**Comment by john-co** [comment]
To avoid rerunning a lot of tests again due to a couple of known test failures in upstream, we're recommending engineering to ask QA to review. If identified that test failures are unrelated, the PR can be manually forward to BChan. Will need to `ci:reopen` on the PR to BChan. I'll go ahead and forward this to BChan since I realized you used `ci:forward` indicating it's ready.

**Comment by john-co** [comment]
pushed to https://github.com/brianchandotcom/liferay-portal/pull/91984

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
