### PR TITLE
LPD-28218 Fix JspAnalyzerPlugin

### PR DESCRIPTION
**Pull request by petershin**
@dantewang

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:stable

**Comment by dantewang** [comment]
@petershin Thank you very much!

**Comment by petershin** [comment]
ci:test:stable

**Comment by petershin** [comment]
Rebased w master: https://github.com/petershin/liferay-portal/pull/2238

**Pull request closed without merging**
