### PR TITLE
LPS-85710 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/63482

**Pull request closed without merging**
