### PR TITLE
LPS-90013 Add date type.

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @petershin,

Types like:

```yml
        dateModified:
          format: date-time
          type: string
``` 

Should be converted to:

```java
	public Date getDateModified() {
		return _dateModified;
	}
```

In this pull I have changed the generator to support this behaviour.

Thanks!

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/67570

**Pull request closed without merging**
