### PR TITLE
LPS-98200 Deprecated

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test

**Comment by jpince** [comment]
@petershin thanks, I'll fetch this branch later today to fix the app.bnd and SF issues and remove `.lfrbuild-portal` so all relevant tests will pass.

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
testing here, gradle-plugins change not needed: https://github.com/jpince/liferay-portal/pull/126

**Pull request closed without merging**
