### PR TITLE
lps-84119

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
cc @gamerson, @jpince, @christopherbryanboyd

**Comment by jpince** [comment]
follow-up to https://github.com/brianchandotcom/liferay-portal/pull/72733/commits/a0e267814a80509a4da6825f446469eae58a3d5e @hhuijser

Does this fix also need to be applied to other places?
@petershin I see a change to `gradle-plugins-whip` and `portal-tools-service-builder`
@pyoo47 @michaelhashimoto see change in `jenkins-result-parser`

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by petershin** [comment]
@lawrence-lee - Can you remove the class and just use `Arrays#asList` or `Collections.singleton` instead?

**Comment by lawrence-lee** [comment]
resent https://github.com/petershin/liferay-portal/pull/494

**Pull request closed without merging**
