### PR TITLE
LPS-109055

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
cc @lawrence-lee

@simonjhy We need to make sure the IDE integration looks ok after this change gets merged.

**Comment by petershin** [comment]
Hi @john-co, do any of the test failures look related to this pull?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
**Reviewed. Test failures are unrelated.** :heavy_check_mark: 
**Verified** test suites: `ci test relevant`, `ci test stable`, `ci test`
**Not verified:** `ci test gradle-plugins`, I couldn't find upstream results to compare against.

**Comparison details:**
[Testray comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1582569754534&testrayRunIdA=1018850996&testrayRunIdB=1018201147)

**Comment by petershin** [comment]
Thank you @john-co!  Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/85185

**Pull request closed without merging**
