### PR TITLE
LPS-123937 Failed to run createDockerContainer task due to invalid volume specification on Windows

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:forward

**Comment by gamerson** [comment]
hey @petershin  all failing tests from the gradle-plugins are from the long-standing classpath bug.

**Pull request closed without merging**
