### PR TITLE
LPS-144364 Add validation for creating war-core-ext project on liferay 73 and greater

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:forwrad

**Comment by petershin** [comment]
ci:forward

**Pull request closed without merging**
