### PR TITLE
lps-92427wchris

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
@petershin, please ask Brian to publish `gradle-plugins-workspace:2.0.2` and `project-templates*`, Tests have passed here: https://github.com/gamerson/liferay-portal/pull/268#issuecomment-491443651

**Comment by petershin** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/73021

**Pull request closed without merging**
