### PR TITLE
Lps 142340

### PR DESCRIPTION
**Pull request by lawrence-lee**
Please publish  `gradle-plugins-workspace`, then `project-templates-*`. Thanks!

### CODE REVIEW

**Comment by lawrence-lee** [comment]
Tests passed here: https://github.com/lawrence-lee/liferay-portal/pull/246#issuecomment-970385390

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:forward

**Pull request closed without merging**
