### PR TITLE
LPS-95688 FAKE GRADLE CACHE project-templates-workspace

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
cc @cody-hoag see here:  https://github.com/petershin/liferay-portal/pull/524/commits/6cbc9cb0e96d82b07cb0ce0bbd2d128da2726180

https://github.com/petershin/liferay-portal/pull/524/commits/9c9164ef4ca1a176ec3143e98a042e4f0f7f99aa

If you have any thoughts on those descrxiptions.

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
ci:test:sf

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/73883

**Pull request closed without merging**
