### PR TITLE
LPS-129940 FormatSourceTask

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Perter,
Issue: https://issues.liferay.com/browse/LPS-129940

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
Forwarding to Brian: https://github.com/petershin/liferay-portal/pull/1401

**Pull request closed without merging**
