### PR TITLE
LPS-116357 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
Please let tests finish before pushing to BChan

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
@lawrence-lee - I'll wait for Javier's changes.

 I think bchan would ask about forcing the version for `com.liferay.portal.test`.  Why is that needed?

**Comment by lawrence-lee** [comment]
@petershin, I've already added @javierdearcos 's changes. 


@javierdearcos can you answer peter's question about `com.liferay.portal.test`. I think its because this is our first project template that includes a test module that actually works with our testIntegration plugin. but I'm not 100% sure on that

**Comment by petershin** [comment]
Everything else looks ok so forwarding it to Brian and see what he says: https://github.com/petershin/liferay-portal/pull/1103

**Comment by javierdearcos** [comment]
> @lawrence-lee - I'll wait for Javier's changes.
> 
> I think bchan would ask about forcing the version for `com.liferay.portal.test`. Why is that needed?

Forcing the version of com.liferay.portal.test is needed to avoid getting a very old version of the module that causes us problems, version 3.0.0. I think this resolution comes from a plugin that uses this old version.

The `gw dependencies` output is:
```
testModules - Configures additional OSGi modules to deploy during integration testing.
+--- com.liferay:com.liferay.arquillian.extension.junit.bridge.connector:1.0.0
+--- com.liferay.portal:com.liferay.portal.test:3.0.0
\--- org.apache.aries.jmx:org.apache.aries.jmx.core:1.1.7
     +--- org.apache.aries.jmx:org.apache.aries.jmx.api:1.1.5
     \--- org.apache.aries:org.apache.aries.util:1.1.1
```

This was a temporary solution until we can check if this plugin dependency could be updated to a newer version.

Thank you very much for all your great work!

**Pull request closed without merging**
