### PR TITLE
LPS-101877 SF

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by petershin** [comment]
@gamerson - The SP is in the process of being released.  Is it ok to wait a day or two before sending this to bchan?  I'm also holding off on sending the `bnd` upgrade for the same reason

**Comment by gamerson** [comment]
Sure.

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/78961

**Pull request closed without merging**
