### PR TITLE
LPS-162929 Fix typos in RootProjectConfigurator and improve exception…

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
Hi @petershin , I have run the tests on https://github.com/Seiphon/liferay-portal/pull/42, but the relevant test failed many times. However I don't think it's related to my fix, so I try to run the tests on your repo

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
Forwarding to Brian: https://github.com/petershin/liferay-portal/pull/1784

**Pull request closed without merging**
