### PR TITLE
LPS-107155 add sf suppression

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
@petershin   The gradle-plugins test is not related to these changes.  All of those target-platform tests pass.

**Comment by petershin** [comment]
Sent to Greg: https://github.com/gamerson/liferay-portal/pull/390

**Pull request closed without merging**
