### PR TITLE
LPS-164541 Rename product as liferayProduct

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
Forwarding to bchan: https://github.com/petershin/liferay-portal/pull/1847

**Pull request closed without merging**
