### PR TITLE
LPS-110422 OsgiHelper

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
@damien-abos - do you know if there's a new api in `Gradle 6` to get the bundle symbolic name?

**Comment by damien-abos** [comment]
Hi @petershin, do you manage the conflict or you like I do? I had some issue to test the solution. I would like to have some directions to improve this PR ;)

**Comment by damien-abos** [comment]
> @damien-abos - do you know if there's a new api in `Gradle 6` to get the bundle symbolic name?

As the package used was deprecated, I didn't see any recommanded replacement. I took a look at gradle release note and found the commit of removal but I do not have any clue for a replacement. That why I choose to replicate the class. The license is compatible :)

**Comment by petershin** [comment]
The code is parsing a string w regex and seems fragile. The thing that would help speed things up is if we can find a replacement in `Gradle` so we don't have to copy the deleted class

Thank you for your contribution.  I'll continue to look into this issue

**Comment by damien-abos** [comment]
In fact, regex are not used in Liferay, the method getVersion is never used and could be safely removed. I kept the integrity of the whole file and add a comment to respect the original authors. 
Only the method getBundleSymbolicName is required.

**Comment by petershin** [comment]
@damien-abos - I removed the unneeded code and forwarded the pull for testing.  https://github.com/petershin/liferay-portal/pull/985

**Pull request closed without merging**
