### PR TITLE
LPS-95388 use latest gradle-plugins-css-builder

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@petershin rebased to latest

**Comment by david-truong** [comment]
@petershin ok this is everything that we need to fix sass-compiler-jni, sass-compiler-ruby, css-builder, gradle-plugins-css-builder...

**Comment by david-truong** [comment]
@petershin one thing I noticed is that by default our gradleTests by default do not use the FAKE GRADLE CACHE... I had to manually add it for each tests.

**Comment by petershin** [comment]
Sent to Dave: https://github.com/david-truong/liferay-portal/pull/116

**Pull request closed without merging**
