### PR TITLE
LPS-105747 Changelogs - Add description section

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @petershin,

See generated file: https://github.com/petershin/liferay-portal/pull/844/commits/6df2f94949481d3025b1f0dd3bd5a9c16778930c

In range `2.0.0:3bf6a2f254e719238a66fa40dc51281fd116507c..2bf5e15d620e41652bc64680bbb421972aade91d`, there is no changes on `gradle-plugins-alloy-taglib/build.gradle`, so we couldn't get anything for this range. So the `date` is empty.

I added `publish date` in `CHANGELOG.descriptions` see: https://github.com/petershin/liferay-portal/pull/844/commits/1da7e6e32a29fbe42978397dd671a40269f2cf8f
If we can't get `publish date` we will use the date from `CHANGELOG.descriptions`.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
cc @hhuijser

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by petershin** [comment]
Hi Alan,

The date can be automatically found by using the commit date.  So for this case in particular, we know the last commit for `2.0.0` is 2bf5e15d620e41652bc64680bbb421972aade91d.  The commit date for that SHA is `2017-04-18`.

`2.0.0:3bf6a2f254e719238a66fa40dc51281fd116507c..2bf5e15d620e41652bc64680bbb421972aade91d`

**Comment by ling-alan-huang** [comment]
Got it, I will resend.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/petershin/liferay-portal/pull/845

**Pull request closed without merging**
