### PR TITLE
LPS-102367 Fix packageRunBuild

### PR DESCRIPTION
**Pull request by petershin**
Hi @wincent, here's the latest and added comments below:

- some `*.js.map`, `*.soy.js`, `*.soy.js.map` files are missing in `node/packageRunBuild/resources`

- are there any other files that Gradle needs to check to see if the task should be rerun

```
project .npmbridgerc
project .npmbundlerrc
project package.json
project package-lock.json
project src/main/resources/META-INF/resources/**
project node/packageRunBuild/resources/**
yarn yarn-1.13.0.js
yarn package.json
yarn yarn.lock
```

@jbalsas

### CODE REVIEW

**Comment by petershin** [comment]
Reminder to deprecate `Gradle` plugins:

```
gradle-plugins-js-module-config-generator
gradle-plugins-js-transpiler
gradle-plugins-soy
```

**Comment by jbalsas** [comment]
Hey @petershin, what do you mean by the reminder? Should we deprecate those? If so... how?

**Comment by petershin** [comment]
@jbalsas - This is something I'll do on my end.  I'm going to deprecate all the classes in these plugins.

**Comment by wincent** [comment]
> some `*.js.map`, `*.soy.js`, `*.soy.js.map` files are missing in `node/packageRunBuild/resources`

Can you give me an example of a module in which this is happening so that I can dig deeper?

> are there any other files that Gradle needs to check to see if the task should be rerun

I'd also add these ones to that list:

- `modules/apps/npmscripts.config.js`
- `modules/apps/*/*/npmscripts.config.js`
- `modules/apps/*/*/webpack.config.js` (only exists in two modules)

**Comment by petershin** [comment]
>Can you give me an example of a module in which this is happening so that I can dig deeper?

An example is `frontend-taglib-clay`.  I diff'd the jar before and after the change:

```
ManagementToolbar.soy.js                                      missing
ManagementToolbar.soy.js.map                                  missing
ClayAlertBase.soy.js                                          not translated
node_modules\@frontend-taglib-clay$clayui%2Fshared@3.0.0\**   added
```

>modules/apps/npmscripts.config.js
>modules/apps/*/*/npmscripts.config.js
>modules/apps/*/*/webpack.config.js (only exists in two modules)

Ok, will add a commit to update the inputs.

**Comment by wincent** [comment]
@petershin: I can't reproduce any of the issues you mentioned above. Here's what I did:

1. Do an `ant all` on today's HEAD of master (8b302b735b6ad41a2613fe502dab0e86834daa98) and grab a copy of the resulting `build/tmp/jar/com.liferay.frontend.taglib.clay-3.0.0.jar`
2. Grab this PR and do a rebase (https://github.com/petershin/liferay-portal/pull/730); no actual changes there, just needed to fix merge conflicts in modules/package.json; do an `ant all` and grab copy of that JAR too.
3. Compare then contents of the JAR; both contain the same 6,394 files:
  - master: https://gist.github.com/wincent/d5f35dba127bb39d297289d11048b64d
  - PR: https://gist.github.com/wincent/4d3754959c75cba0bfe724cbefed847e
4. Inspect the contents of `./META-INF/resources/node_modules/frontend-taglib-clay$clay-alert@2.18.1/lib/ClayAlertBase.soy.js` on both branches; verify that both have `Liferay.Language.get()` correctly substituted:
  - master: https://gist.github.com/wincent/a26824b461eb92ba035c5b9fc83f44fa#file-clayalertbase-soy-js-L188
  - PR: https://gist.github.com/wincent/a6c64498b1d3cb092a63b11fdfd818fd#file-clayalertbase-soy-js-L188

**Comment by jbalsas** [comment]
@petershin, you won't be running on Windows by any chance?

**Comment by wincent** [comment]
After a two-hour `ant all` on the venerable Windows laptop here, I think I can reproduce the issues. Digging deeper.

**Comment by wincent** [comment]
Ok, I applied a small fix to address the soy files not getting updated when building on Windows: updated https://github.com/petershin/liferay-portal/pull/730 with that (ie. bumps liferay-npm-scripts version to v10.1.1).

When doing a `clean` followed by a full build on Windows, I no longer see the problems listed in @petershin's [comment above](https://github.com/petershin/liferay-portal/pull/724#issuecomment-537253992). Specifically, I see:

- List of files in jar exactly match between master (built on Mac) and #730 (built on Windows).
  - ManagementToolbar.soy.js (and map) not missing.
  - No extra files under node_modules\@frontend-taglib-clay$clayui%2Fshared@3.0.0\**   added
  - Both have [the same 6,493 files](https://gist.github.com/wincent/3e2c8926140550ef37a8d3a0c58a5fb3).
- `ClayAlertBase.soy.js` is translated.

**Comment by petershin** [comment]
@jbalsas - Yup, I'm using windows.

Thank you @wincent! Running the `CI` tests here: https://github.com/petershin/liferay-portal/pull/731

I'll run some tests locally too.

**Comment by petershin** [comment]
The `CI` results looked ok to me.  Will ask QA to do a more thorough check.

I'm going to do some more tests tomorrow.  If everything goes well, will send to bchan Friday morning.

**Comment by petershin** [comment]
@wincent - For pre-7.2.x, I removed the custom `Gradle` stale check for the `packageRunBuild` task. The jars that I generated weren't the same and this might mean that the stale check wasn't the problem.

The pull https://github.com/wincent/liferay-portal-ee/pull/3 has the different generated jars along w the code that removes the stale check for the `packageRunBuild` task.

Can you run these tests and see if you're able to create the different jars too?

> git checkout 7.1.x
> git rebase upstream/7.1.x
> cd modules\apps\frontend-taglib\frontend-taglib-clay
> git clean -fdx
> gw clean
> gw jar
> save Jar A

> git checkout [my pull]
> gw jar
> save Jar B

> git clean -fdx
> gw clean
> gw jar
> save Jar C

> gw jar
> save Jar D

**Comment by jbalsas** [comment]
Hey @petershin, can you detail a bit more what's the goal of that PR in `7.1.x`? What are we looking to do there? Is it really necessary? Are we trying to fix a specific problem? What are your expectations about those jars and why?

**Comment by petershin** [comment]
Followed up w Chema on slack and the fix will likely take a few days.

The output of `liferay-npm-scripts` needs to be consistent whenever its run, not just during `ant all`.  There'd be unusual errors w even a simple `deploy` and no obvious way for a dev to fix the issue w/o running `ant all`.  I saw glimpses of this problem on `master` and made a comment about it earlier.

As a future task on my end, the unused Gradle plugins need to be removed to simplify the build.  These plugins should still be available for clients on the older `7.x` branches.  As a start, they'll be marked as deprecated as part of the changes in this pull.  See https://github.com/petershin/liferay-portal/pull/733

**Comment by wincent** [comment]
> The output of `liferay-npm-scripts` needs to be consistent whenever its run

In theory `liferay-npm-scripts` doesn't care whether it's run from `ant` or `gradlew` or `yarn` or directly, but I can see that some of the tooling that it relies upon may not be guaranteed to be idempotent (that is, Babel, or webpack, or the bundler might conceivably have generate some non-deterministic IDs as they write their output). I'll ask Chema for more details on Monday.

**Comment by jbalsas** [comment]
@petershin, now that SP1 is out the door... when do you think we could land this in? We have several things depending on this to get in before we can rebase and merge, so the sooner the better :)

**Comment by petershin** [comment]
@jbalsas - As soon as the `liferay-npm-scripts` build issue is fixed.

**Comment by petershin** [comment]
@jbalsas - I'll send you a pull and the steps to reproduce the different failures on `master`.

**Comment by petershin** [comment]
Each of the jars below should be the same.  I used Jar A as the standard

> git checkout f29d4f918914 (master earlier this morning)
> ant all
> save Jar A

> cd modules\apps\frontend-taglib\frontend-taglib-clay
> gw jar
> save Jar B
```
extra **\*.js.map files
```

> git checkout https://github.com/jbalsas/liferay-portal/pull/1968
> gw jar
> save Jar C
```
missing META-INF\resources\bride\**\*.js
missing META-INF\resources\node_modules\**\*.js
extra META-INF\resources\bride\**\*.js.map files
```

> git clean -fdx
> gw jar
> save Jar D
```
missing META-INF\resources\node_modules\@frontend-taglib-clay$clayui%2Fshared@3.0.0\**
```

> gw jar
> save Jar E
```
extra **\*.js.map files
missing META-INF\resources\node_modules\@frontend-taglib-clay$clayui%2Fshared@3.0.0\**
```

**Comment by petershin** [comment]
@jbalsas, @wincent - Rebased w the latest and temporarily removed the `Gradle` caching logic

**Comment by jbalsas** [comment]
See https://github.com/petershin/liferay-portal/pull/735, @petershin

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co, tests here look worse than in the past... could you please analyze these results?

Thanks!

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:bundle:norebase

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:norebase

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test

**Comment by wincent** [comment]
@petershin, @jbalsas: I just sent https://github.com/petershin/liferay-portal/pull/743 which takes this PR and updates it to use liferay-npm-scripts v12.0.0-beta.1 (basically the same as used here but with the `@clayui` import version ranges updated to the latest). Will run tests over there and if they look good, cut v12.0.0 final and update the PR to use that instead.

**Pull request closed without merging**
