### PR TITLE
LPS-85609 Gradle

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@pyoo47 - Do you know what caused the build to be aborted?

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by pyoo47** [comment]
@petershin It looks like the gradle-test-plugins-jdk8 job froze and timed out.

```
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
```

Here's a snippet of the last bit of console log that printed before the timeout logic kicked in..

```
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] > Task :sdk:gradle-plugins-tlddoc-builder:gradleTestGenerator
     [exec] > Task :sdk:gradle-plugins-tlddoc-builder:compileGradleTestGroovy
     [exec] > Task :sdk:gradle-plugins-tlddoc-builder:copyGradleTestDependencies
     [exec] > Task :sdk:gradle-plugins-tlddoc-builder:processGradleTestResources NO-SOURCE
     [exec] > Task :sdk:gradle-plugins-tlddoc-builder:gradleTestClasses
     [exec] > Task :sdk:gradle-plugins-tlddoc-builder:gradleTestClasspathManifest
     [exec] > Task :sdk:gradle-plugins-tlddoc-builder:autoUpdateXml SKIPPED
     [exec] > Task :sdk:gradle-plugins-tlddoc-builder:jar
     [exec] > Task :sdk:gradle-plugins-tlddoc-builder:prepareGradleTestInputs
     [exec] > Task :sdk:gradle-plugins-tlddoc-builder:gradleTest
[liferay-jenkins-ee] $ /bin/bash -e -x /tmp/jenkins7084350681826992636.sh
+ echo 'Execute: build-test-portal-acceptance-pullrequest-batch.sh build-timeout-operations'
Execute: build-test-portal-acceptance-pullrequest-batch.sh build-timeout-operations
+ commands/build-test-portal-acceptance-pullrequest-batch.sh build-timeout-operations
Execute: ant -f commands/build-test-portal-acceptance-pullrequest-batch.xml build-timeout-operations
Buildfile: /opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest-batch.xml

build-timeout-operations:
```

**Comment by petershin** [comment]
@pyoo47 - Just brainstorming ideas, would it be possible/better to split the `gradle-plugins` test suite into multiple jobs?

**Comment by pyoo47** [comment]
@petershin The timeout is set on a jenkins job basis so it's not really practical to try to customize it for a particular test-suite. Splitting the tasks into separate Jenkins axes is a more practical approach.

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Pull request closed without merging**
