### PR TITLE
LPS-129874

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
ci:close

**Comment by lawrence-lee** [comment]
Test failed https://github.com/petershin/liferay-portal/pull/1394

**Comment by lawrence-lee** [comment]
i'm not sure what's going on but they passed locally and when i ran them here: https://github.com/lawrence-lee/liferay-portal/pull/205

**Pull request closed without merging**
