### PR TITLE
LPS-103547 Move task to BaselineDefaultsPlugin

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Peter,

https://issues.liferay.com/browse/LPS-103547

Thanks.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
cc: @hhuijser

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:gradle-plugins

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@ling-alan-huang - there needs to be a few changes.

I'm thinking it through before going over it with you

**Comment by petershin** [comment]
Hi @ling-alan-huang, this is very close to what needs to be done.  It does this:

```
xxx-service:baseline ->
xxx-service:buildService
xxx-service:baseline
```

What the existing Gradle code does is this

```
xxx-service:buildService ->
xxx-service:buildService
xxx-api:baseline
```

After taking a closer look, it'd be simpler to put the logic in `ServiceBuilderDefaultsPlugin.java`.

**Comment by ling-alan-huang** [comment]
Hi @petershin,

I need your help.

I am trying to move [if (apiDir != null) {](https://github.com/petershin/liferay-portal/pull/761/commits/8536af72e98c3415ed88e646217e89c22a7619e4#diff-5fd3a45c999b9033d241682ab636556dL127) to [ServiceBuilderDefaultsPlugin.java](https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins/src/main/java/com/liferay/gradle/plugins/internal/ServiceBuilderDefaultsPlugin.java#L65) by adding `buildServiceTask.getApiDir()`, but `buildServiceTask.getApiDir()` always returns `null`, why `apiDir` is not `null` in build.gradle ?

Thanks.

**Comment by petershin** [comment]
@ling-alan-huang - The properties in `Gradle` are evaluated at different times (mainly to run things faster).  In this case we'll need to wrap the code in an `afterEvaluate` block similar to the original code.  See [modules/build.gradle#L108](https://github.com/liferay/liferay-portal/blob/master/modules/build.gradle#L108)

In Java, it translates to something like this:

```
project.afterEvaluate(
	new Action<Project>() {

		@Override
		public void execute(Project project) {
		}

	});
```

**Comment by ling-alan-huang** [comment]
Thanks again @petershin, resent: https://github.com/petershin/liferay-portal/pull/768

**Pull request closed without merging**
