### PR TITLE
LPD-26910 Fix compileJava inputs/outputs

### PR DESCRIPTION
**Pull request by petershin**
@pyoo47 @michaelhashimoto

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by michaelhashimoto** [comment]
Hey @petershin,

@kenjiheigel found out that there are failures that are likely only found in this pull request.
https://gist.github.com/kenjiheigel/9cb0a595e1107b542e8e58a955597bb9

What we observed is that the duration of the test tasks is taking much longer, which likely is the reason these tests are failing.  A majority of the tests seem to be failing because the downstream builds are being aborted.

@pyoo47 thought that maybe it could be because we have build caches enabled, so we are going to try running it one more time with the credentials enabled to see if we get better results.

**Comment by petershin** [comment]
ci:report:20533271

**Comment by petershin** [comment]
ci:report:20822326

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:forward:force

**Pull request closed without merging**
