### PR TITLE
LPS-98417 Add jsCompile to whitelist for TP configurations

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
@petershin  both of those errors may be spurious nodejs build failures.

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@gamerson - For flaky tests, please fix them when possible.  Installed TP and workspace to the local cache to fix the test classpath issues.  Running tests here: https://github.com/petershin/liferay-portal/pull/972

**Pull request closed without merging**
