### PR TITLE
LPS-93483 liferay-js project support in modules folder

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
hey @petershin   This is one of those pesky classpath errors.  It is saying that it can't find this method:

```
Caused by: java.lang.NoSuchMethodError: com.liferay.gradle.plugins.workspace.internal.util.FileUtil.getJavaClassesDir(Lorg/gradle/api/tasks/SourceSet;)Ljava/io/File;

``` this is obviously a method that has existed in gradle-util.jar, but for some reason this is seeing any older version.

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/76520

**Pull request closed without merging**
