### PR TITLE
LPS-158703 Simplify the templates of rest buidler project

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
Hi @petershin , tests are passed here https://github.com/Seiphon/liferay-portal/pull/32

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:forward

**Pull request closed without merging**
