### PR TITLE
LPS-89415 Fix buildREST

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Peter:

_**Original PR:**_
https://github.com/brianchandotcom/liferay-portal/pull/79231

_**My fix:**_

**Fix 1:** Added SF check - YMLLongLinesCheck( Already merged on master)

With this fix, when I run `gw buildREST`,  `rest-openapi.yaml `will be  overwritten

from:
```
    "/sites/{siteId}/user-accounts/{userAccountId}/segments":
        get:
            description: This is long multiline description, xxx yyy
               zzz
            operationId: getSiteUserAccountSegmentsPage

```
to 
```
    "/sites/{siteId}/user-accounts/{userAccountId}/segments":
        get:
            description: This is long multiline description, xxx yyy
            operationId: getSiteUserAccountSegmentsPage
               zzz

```

and BUILD FAILED.

---------------------------------

**Fix 2:** Change logic(RESTBuilder.java) to consider multiline

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
cc: @hhuijser, @dgarciasarai

**Comment by dgarciasarai** [comment]
Any update? We have a blocked task depending on this to add long descriptions to OpenAPI schemas. Thanks.

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/79642

**Pull request closed without merging**
