### PR TITLE
COMMERCE-4052 Fix testIntegration

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by jpince** [comment]
@petershin I think there are still a lot of tests that the Commerce team will have to fix themselves (many have already failed in the [test run](https://test-1-9.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3655/jenkins-report.html)). I recommend manually forwarding this to BChan as part of the overall Commerce test fix effort :smile: 

cc/ @marco-leo

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/93471

**Comment by petershin** [comment]
ci:stop

**Pull request closed without merging**
