### PR TITLE
LPS-96590 custom build profile support based on project dependencies

### PR DESCRIPTION
**Pull request by gamerson**
@sammonsjl @arboliveira

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Reviewing the changes with Greg.

**Comment by gamerson** [comment]
Thanks Peter for initial review, I'll send a new one soon.

**Pull request closed without merging**
