### PR TITLE
LPS-0 Add LiferayYarnPlugin

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
Hi @john-co, do these failures look known issues?

**Comment by john-co** [comment]
Just started analyzing :)

**Comment by john-co** [comment]
These test batch failures look unique:
test-portal-acceptance-pullrequest-batch(master)/portal-license-jdk8
test-portal-acceptance-pullrequest-batch(master)/release-osgi-state-lpkg-change-directory-test-jdk8

**Comment by petershin** [comment]
@john-co - Is there a way to rerun just the `portal-license-jdk8` test?

The performance team said the `release-osgi-state-lpkg-change-directory-test-jdk8` failure is not related to these changes.

**Comment by john-co** [comment]
testing `portal-license-jdk8` on: https://github.com/john-co/liferay-portal/pull/169

**Comment by john-co** [comment]
@petershin `portal-license-jdk8` passed on john-co#169 :heavy_check_mark:

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/77295

**Pull request closed without merging**
