### PR TITLE
LPS-148304 Annotations

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:forward

**Comment by yhtMinceraft1010X** [comment]
@petershin Thank you for reviewing the PR. 

After trying out the latest release of the plugin on a project, I realised that my suggested annotations are still not compatible with Gradle 7. As such, I wish to make some changes to the solution that I initially proposed in the following 2 files:
* https://github.com/yhtMinceraft1010X/liferay-portal/commit/53b0e94fff070cde2ebfa51742926e64794d152b
* https://github.com/yhtMinceraft1010X/liferay-portal/commit/455e0849dc0b7158682e648db77cab5af189e44d

Thank you and sry for the inconvenience.

**Comment by petershin** [comment]
@yhtMinceraft1010X - Do you have the steps to show the incompatibility error messages? The PathSensitive changes make sense, I'm wondering why the Optional annotations had to be removed.

**Comment by yhtMinceraft1010X** [comment]
@petershin Here's my build output after running a task of type `ExecutePackageManagerTask` with `--warning-mode all` using the latest release. 
Screenshot (286)

According to Gradle, the `@Optional` annotation is not meant to be used with the primitive types.

**Comment by petershin** [comment]
@yhtMinceraft1010X - Running the CI tests here: https://github.com/petershin/liferay-portal/pull/1659

**Comment by yhtMinceraft1010X** [comment]
@petershin Thanks for your help! I've just tested `7.2.18` and `ExecutePackageManagerTask` now works on Gradle 7.4.2.

**Pull request closed without merging**
