### PR TITLE
LPS-84119 Use 'absolutePath' instead of 'fileName' to check the path

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @petershin,

I will forward this issue via mail.

Thanks.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to this pull.

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/67495

**Pull request closed without merging**
