### PR TITLE
LPS-105747 Changlogs

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Peter,

I added some CHANGELOG.descriptions files.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
cc: @hhuijser

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/84402

In a separate pull, please remove the unneeded line below:

https://github.com/petershin/liferay-portal/pull/872/commits/15802c355c9b680cdae7827e5bcc342c88b42b28#diff-8f9d5a46da5492631a69d5169cdf529aR80

**Comment by ling-alan-huang** [comment]
> Sent to Brian: [brianchandotcom#84402](https://github.com/brianchandotcom/liferay-portal/pull/84402)
> 
> In a separate pull, please remove the unneeded line below:
> 
> [15802c3#diff-8f9d5a46da5492631a69d5169cdf529aR80](https://github.com/petershin/liferay-portal/commit/15802c355c9b680cdae7827e5bcc342c88b42b28#diff-8f9d5a46da5492631a69d5169cdf529aR80)

@petershin, just want to check with you.

That line is from commit c546ef4a7e2545997bd0e4341febe9f1031a97bd
`c546ef4a7e2545997bd0e4341febe9f1031a97bd:2017-10-04:Revert "LPS-74110 prep next, use latest"`
This commit reverted  dependency from `2.0.41` to `2.0.40`, that means `gradle-plugins-baseline`is still use `2.0.40` in **gradle-plugins-baseline(1.1.8)**

If we remove that line, that mean we use `2.0.41` in **gradle-plugins-baseline(1.1.8)**.
So I think we should keep this line.

------------------------
Some of diffs:
```
c546ef4a7e2545997bd0e4341febe9f1031a97bd:2017-10-04:Revert "LPS-74110 prep next, use latest"
diff --git a/modules/sdk/gradle-plugins-baseline/build.gradle b/modules/sdk/gradle-plugins-baseline/build.gradle
index da71c304e4c0..90a74132a1fe 100644
--- a/modules/sdk/gradle-plugins-baseline/build.gradle
+++ b/modules/sdk/gradle-plugins-baseline/build.gradle
@@ -11,7 +11,7 @@ copyGradleTestDependencies {
 }
 
 dependencies {
-	compile group: "com.liferay", name: "com.liferay.ant.bnd", version: "2.0.41"
+	compile group: "com.liferay", name: "com.liferay.ant.bnd", version: "2.0.40"
 	compile group: "com.liferay", name: "com.liferay.gradle.util", version: "1.0.29"
 
 	compileOnly fileTree(builtBy: [rootProject.tasks.extractGradleApi25], dir: new File(rootProject.buildDir, "gradle-2.5"))

ee89dbce943b2ca6e4fb4541ae8e95bf3ba15478:2017-10-02:LPS-74110 prep next, use latest
diff --git a/modules/sdk/gradle-plugins-baseline/build.gradle b/modules/sdk/gradle-plugins-baseline/build.gradle
index 90a74132a1fe..da71c304e4c0 100644
--- a/modules/sdk/gradle-plugins-baseline/build.gradle
+++ b/modules/sdk/gradle-plugins-baseline/build.gradle
@@ -11,7 +11,7 @@ copyGradleTestDependencies {
 }
 
 dependencies {
-	compile group: "com.liferay", name: "com.liferay.ant.bnd", version: "2.0.40"
+	compile group: "com.liferay", name: "com.liferay.ant.bnd", version: "2.0.41"
 	compile group: "com.liferay", name: "com.liferay.gradle.util", version: "1.0.29"
 
 	compileOnly fileTree(builtBy: [rootProject.tasks.extractGradleApi25], dir: new File(rootProject.buildDir, "gradle-2.5"))

dced8f4cd14a63bfd764de0dae160141bb274f49:2017-09-11:LPS-73481 Use latest ant-bnd
diff --git a/modules/sdk/gradle-plugins-baseline/build.gradle b/modules/sdk/gradle-plugins-baseline/build.gradle
index 5d834668168b..90a74132a1fe 100644
--- a/modules/sdk/gradle-plugins-baseline/build.gradle
+++ b/modules/sdk/gradle-plugins-baseline/build.gradle
@@ -11,7 +11,7 @@ copyGradleTestDependencies {
 }
 
 dependencies {
-	compile group: "com.liferay", name: "com.liferay.ant.bnd", version: "2.0.39"
+	compile group: "com.liferay", name: "com.liferay.ant.bnd", version: "2.0.40"
 	compile group: "com.liferay", name: "com.liferay.gradle.util", version: "1.0.29"
 
 	compileOnly fileTree(builtBy: [rootProject.tasks.extractGradleApi25], dir: new File(rootProject.buildDir, "gradle-2.5"))
```

**Comment by ling-alan-huang** [comment]
Hi @petershin, I just added a comment, please see above.

**Comment by petershin** [comment]
@ling-alan-huang - You're right.  Sent a pull to fix the ticket numbers: https://github.com/brianchandotcom/liferay-portal/pull/84525

**Pull request closed without merging**
