### PR TITLE
LPS-101060 fixup version matcher for suffixed qualifiers

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@gamerson - can you take a look at the `gradle-plugins-target-platform` failure in the first `ci:test:gradle-plugin`. I think that's a real issue, but unrelated to the changes in this pull

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/78002

**Pull request closed without merging**
