### PR TITLE
LPS-111070 Fix baseline task

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
@pyoo47 - this error looks unrelated. how should I forward this pull to bchan?

**Comment by pyoo47** [comment]
@petershin Unfortunately, the only way is to wait for a fix to get merged to upstream. That may consist of either a real fix or a commit that removes the test. The best place to inquire about the status of any such fixes is in [d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Comment by petershin** [comment]
@pyoo47 - Got it.  I'll try again on Monday

**Comment by petershin** [comment]
See https://github.com/petershin/liferay-portal/pull/931

**Pull request closed without merging**
