### PR TITLE
LPS-103547 Move logic to ServiceBuilderDefaultsPlugin

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Thanks @petershin,

https://issues.liferay.com/browse/LPS-103547

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
Hi Alan, some customers apply just `gradle-plugins`, so I moved the logic to `gradle-plugins-defaults` to avoid breaking those projects. Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/80193

**Pull request closed without merging**
