### PR TITLE
lps-99895

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
hey @petershin, do you know why i'm getting this error? https://github.com/petershin/liferay-portal/pull/661#issuecomment-523725422

**Comment by petershin** [comment]
@lawrence-lee - Taking a look

**Comment by petershin** [comment]
@lawrence-lee - I see the problem, will send a fix

**Comment by petershin** [comment]
Sent an update pull: https://github.com/petershin/liferay-portal/pull/662

**Pull request closed without merging**
