### PR TITLE
LPS-105232 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
@javierdearcos, Do you know why the version `com.liferay.portal.tools.rest.builder` keeps changing even though `com.liferay.gradle.plugins` and `com.liferay.gradle.plugins.workspace` stay the same? 

There must be some code in `com.liferay.gradle.plugins` that keeps pulling the latest version of `com.liferay.portal.tools.rest.builder`. We had to fix a similar problem before with `com.liferay.css.builder` and we had to fix it using a custom configuration.

**Comment by petershin** [comment]
@lawrence-lee - It's intended to always pull the latest

https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins/src/main/resources/com/liferay/gradle/plugins/dependencies/portal-tools.properties#L9

**Comment by lawrence-lee** [comment]
@petershin , is this a recent change? I know we used to be able to lock it down with a static version of `com.liferay.gradle.plugins` 
for example `com.liferay.gradle.plugins:7.0.17` 
i see `com.liferay:com.liferay.source.formatter:1.0.1007` and `com.liferay:com.liferay.portal.tools.service.builder:1.0.343`

**Comment by petershin** [comment]
@lawrence-lee - It hasn't changed.  Just in case this helps, latest means the latest published version (not the local version).

**Comment by lawrence-lee** [comment]
Going to send a followup PR

**Comment by lawrence-lee** [comment]
Sent here: https://github.com/javierdearcos/liferay-portal/pull/33

**Pull request closed without merging**
