### PR TITLE
LPS-102342 Update liferay-npm-scripts to v12.0.0-beta.1

### PR DESCRIPTION
**Pull request by wincent**
This takes the latest state of https://github.com/petershin/liferay-portal/pull/724 (ie. commit b35486b55709ce) and applies one more commit on top of that for testing purposes: updates to liferay-npm-scripts v12.0.0-beta.1 (which updates the versions used in the `@clayui` imports).

If the tests look good on this, I'll cut v12.0.0 final and update this PR to use that instead.

"master-private" equivalent of this PR: https://github.com/petershin/liferay-portal-ee/pull/172

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test

**Comment by jbalsas** [comment]
Comparing with https://github.com/brianchandotcom/liferay-portal/pull/79545 I see some additional failures... so there might be something off after all.

However, it might simply be that `private` needs to be updated too before getting it green.

@petershin, what do you think? Do these look good enough to cut a final release of `npm-scripts` that we can push forward?

@john-co, could you review these?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
These functional test failures look related:
- CPPortalSettings and PortalSmokeUpgrade tests
clicking on CP > Configuration > Instance Settings > User Authentication, throws warning:
```
     [exec]     LIFERAY_ERROR: Default value "," for attribute definition "csvFileColumnDelimiter" is invalid because "Cardinality violation: "," has 2 value(s) but must have between 1 and 1 value(s).". 
     [exec]     LIFERAY_ERROR: Invalid default value "," for attribute definition "csvFileColumnDelimiter" in metadata XML at "bundleentry://711.fwk1930842682/OSGI-INF/metatype/com.liferay.batch.engine.configuration.BatchEngineTaskConfiguration.xml" for bundle ID "711" with symbolic name "com.liferay.batch.engine.api". 
```

Will review backend tests.

**Comment by john-co** [comment]
The following backend test failures look unique:
- archived-modules-test-jdk8
https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/194805/
- js-unit-private-jdk8
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/324637/

**Comment by jbalsas** [comment]
Not sure how CPPortalSettings and PortalSmokeUpgrade can be related... we don't touch xmls at all which is what seems to fail... are those warnings on the server?

**Comment by jbalsas** [comment]
I think the `js-unit-private` should be addressed at https://github.com/brianchandotcom/liferay-portal-ee/pull/27047

**Comment by jbalsas** [comment]
I also don't see how `archived-modules-test-jdk8` can be related... 🤔

**Comment by john-co** [comment]
ci:test:bundle:norebase

**Comment by john-co** [comment]
ci:test

**Comment by petershin** [comment]
@jbalsas - The local jar tests look much better!  If John says the `CI` tests look ok, I'll send @wincent a pull with the very latest so he can update the `liferay-npm-script` version

There's two minor notes:

- I can create a situation where there are `import` statements are in the `**.es.js` files, but this can be fixed in a separate pull if needed.  Steps to reproduce are below:

  > git checkout c5a1d6f87ed1dbb9bd59b6a4b3fd45395330810d (master before our changes)
  > ant all
  > cd modules\apps\frontend-taglib\frontend-taglib-clay
  > gw jar
  > git checkout https://github.com/petershin/liferay-portal/pull/743
  > gw jar
  > there are `import` statements in `ManagementToolbar.es.js`

- the jar problem will still exist in the `7.1.x` and `7.0.x` branches for projects that use the `liferay-npm-scripts`. the jar is only reliable after running an `ant all`. I can provide separate steps to reproduce if its helpful

@brianchandotcom

**Comment by john-co** [comment]
`archived-modules-test-jdk8` still looks unique. But I believe this would be resolved by rebasing since it looks like the pull is missing this revert: https://github.com/liferay/liferay-portal/commit/2592bacc00ea8da2501c2bb22720f8eb01377b9a

All other test failures look unrelated.

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
changes were committed to head, retesting.

**Comment by john-co** [comment]
@petershin could you update the gradle files when you get the chance?

**Comment by petershin** [comment]
Rebased with the latest in master: https://github.com/petershin/liferay-portal/pull/747

**Comment by jbalsas** [comment]
Hey @petershin, just reviewed the case you mentioned. The steps you described would be equivalent to:

> git checkout c5a1d6f (master before our changes)
> ant all
> cd modules\apps\frontend-taglib\frontend-taglib-clay
> gw jar
> gw jar

At this point, we're basically just running `gw jar` twice in succession because we never fetch the new version of the scripts. If we were to follow these same steps after we land these changes, then the effect would be somewhat similar in that you're not compiling with a newer version of the tools as expected.

After checking out the new branch, you'd need to run `ant setup-yarn` in order for the new scripts to be downloaded. This should be similar to the `FAKE GRADLE CACHE` or something like that. Is there a way we can check that so we re-run `ant setup-yarn` if the `yarn.lock` file is different than in the previous invocation?

**Comment by petershin** [comment]
@jbalsas - Yup, the inputs and outputs for the `yarn install` task need to be updated.  Will add a fix in a separate pull.

@john-co - How do the CI tests look in the new pull? https://github.com/petershin/liferay-portal/pull/747

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Looks like the previous tests are now passing and verified a couple of the unique functional tests pass locally. Looks good to me! :+1: 

Compare:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=830828934&testrayRunIdA=830993196&statusB=2

ExportImport#ExportImportValidation - Passes locally 
CPWiki#AddFrontPage - Passes locally

/cc @petershin

**Pull request closed without merging**
