### PR TITLE
LPS-95279 Workspace and Target Platform improvements

### PR DESCRIPTION
**Pull request by gamerson**
cc @david-truong

Thanks @rotty3000 for all the help with the redesign.  I still need to followup with more Workspace template changes (and other template changes) but this lays the groundwork for all future changes.

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
hey @petershin  I didn't send in any change logs but i will now.

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:sf

**Comment by petershin** [comment]
@gamerson - Rebased w the latest and started tests here: https://github.com/petershin/liferay-portal/pull/514

**Pull request closed without merging**
