### PR TITLE
LPS-0 Yarn rename tasks

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:project-templates

**Comment by john-co** [comment]
Hi @petershin, The functional tests failures are not related to the pull. The other backend batch failures have been reproduced in another pull earlier today as well. So the failures don't seem related besides the project-template failure that you mentioned.

**Comment by john-co** [comment]
ci:test

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
@john-co - There's an issue with `CI` that Peter Yoo is investigating.  I'll retest the pull with the latest once that issue has been resolved

**Pull request closed without merging**
