### PR TITLE
LPD-15162 Java 21

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:relevant:norebase

**Comment by petershin** [comment]
ci:test:sf:norebase

**Comment by vicnate5** [comment]
ci:report:2555874865

**Comment by petershin** [comment]
ci:test:sf:norebase

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:report:2558280279

**Comment by petershin** [comment]
ci:reevaluate:1277401_11564

**Pull request closed without merging**
