### PR TITLE
LPS-83067

### PR DESCRIPTION
**Pull request by Ithildir**
Hi @petershin!
Another task for you: this pull tries to enable a particular form of "multiple" semantic versioning check. For instance, now that `portal-kernel` in `master` is 4.x.y, we want to test it with both the greatest artifact in the range `[3.0.0, 4.0.0[` (that is, from the `7.1.x` branch) and the greatest one in the range `[2.0.0, 3.0.0[` (that is, from the `7.0.x` branch). The reason for this is that, if we add a method in `7.0.x`, publish a new 2.x.y `portal-kernel` but forget to forward-port that method to `master`, we should catch this problem.

Shuyang asked me to remove all the `portal-compat` modules that can be safely removed from `master`, and this task is related to this new baseline check. I don't remember what the problem in this pull was, probably you'll have to keep some more `portal-compat` modules (not all of them can be deleted).

Thank you so much for your help! 😊

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:reopen

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
Readded `com.liferay.portal.kernel.util.compat`. See https://github.com/petershin/liferay-portal/pull/165

**Pull request closed without merging**
