### PR TITLE
LPS-102367

### PR DESCRIPTION
**Pull request by petershin**
@jbalsas @wincent @john-co

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

see https://github.com/petershin/liferay-portal/pull/743#issuecomment-542790377 for details

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/79661

**Pull request closed without merging**
