### PR TITLE
LPS-86528 refactor version handling to new util and add tests

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
@petershin  can you ask Brian to publish `gradle-plugins-workspace`? thanks.

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
Made a minor change to follow the `as used` principle: https://github.com/brianchandotcom/liferay-portal/pull/64371/commits/68460e86868fb51243309ef72830a6b7a2943928

Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/64371

**Pull request closed without merging**
