### PR TITLE
LPS-114705 Task "startTestableTomcat" does not wait for a newly started Tomcat to become reachable, leading to integration tests running while system objects still being created, and DataGuardTestRule deleting system objects created in the middle of tests

### PR DESCRIPTION
**Pull request by arboliveira**
Hi @petershin, this is my first Gradle plugin fix - please let me know if I'm missing any of the appropriate coding conventions  😅 

We need this to fix https://issues.liferay.com/browse/LPS-114021.

cc/ @BryanEngler @shuyangzhou

Explanation of the fix at: https://issues.liferay.com/browse/LPS-114705

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
Solved conflicts, rebased.

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by petershin** [comment]
Forwarding to Brian: https://github.com/petershin/liferay-portal/pull/1021

**Pull request closed without merging**
