### PR TITLE
LPS-96611 fix compileInclude instruction for liferay workspace

### PR DESCRIPTION
**Pull request by gamerson**
cc
@yanan 
@lawrence-lee

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/74657

**Pull request closed without merging**
