### PR TITLE
LRCI-844 Skip dxp projects by default, check build profile before deploying osgi apps

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-844

I prepared the backport branches here:
`7.0.x`: https://github.com/yichenroy/liferay-portal-ee/commits/LRCI-844-skip-dxp-project-by-default-fix-subrepo-test-7.0.x
`7.1.x`: https://github.com/yichenroy/liferay-portal-ee/commits/LRCI-844-skip-dxp-project-by-default-fix-subrepo-test-7.1.x
`7.2.x`: https://github.com/yichenroy/liferay-portal-ee/commits/LRCI-844-skip-dxp-project-by-default-fix-subrepo-test-7.2.x

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by ethanbustad** [comment]
^ looks like portal failures, my guess is not relevant to these changes

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/81842

**Pull request closed without merging**
