### PR TITLE
LPS-111915 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
@petershin and @jpince, i tested this locally and it passed, but I dont know if you want to let the tests finish so we dont introduce more failures to upstream.

**Comment by jpince** [comment]
@lawrence-lee don't forget to revert the ignore https://github.com/brianchandotcom/liferay-portal/commit/0288910058cfe542eb9cb76eed7fd496ab4e0133 (you'll need to rebase on BChan's origin)

It's up to you guys if you want to wait for test results, it'll take around 5-6 hours. I think the risk of introducing new regressions specifically for that test in the meantime is pretty low.

**Comment by jpince** [comment]
@lawrence-lee did you mean to use a different ticket?
[LPS-111915](https://issues.liferay.com/browse/LPS-111915) - Unable to preview display page template in draft web content

**Comment by jpince** [comment]
@lawrence-lee did you mean to use a different ticket?
[LPS-111915](https://issues.liferay.com/browse/LPS-111915) - Unable to preview display page template in draft web content

**Comment by lawrence-lee** [comment]
Hey @petershin @jpince,

Can we let these tests finish since CI seems to be moving slowly? I dont want to introduce more regressions in other tests. I'm not sure how that JSPAnalyzer change will impact our builds

**Comment by lawrence-lee** [comment]
If the tests pass, I'll send a followup PR with the correct LPS ticket as well. Thanks

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/87847

**Pull request closed without merging**
