### PR TITLE
LPS-104028 Run buildCSS faster

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
Hi @john-co, do any of the test failures look related to this pull?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by john-co** [comment]
Comparison:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=869029622&testrayRunIdA=869125056&statusB=2

ContentPagesWithSearch#FilterByPageFacet - 1% flaky test
Forms#PreviewAndPublishForm - looks like a fluke, whitespace was not correctly entered in "TextField" label

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/80887

**Pull request closed without merging**
