### PR TITLE
LPS-97550 exclude conflicting bnd versions

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
sigh, need more debug.

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@gamerson - If it passes the second time, I think you need to open a new pull to reproduce the failure.

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
Resent here along with new solution for arquillian/testIntegration https://github.com/gamerson/liferay-portal/pull/296

**Pull request closed without merging**
