### PR TITLE
LPS-99047

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-99047

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by petershin** [comment]
@holatuwol - In `Gradle` if a task is re-run and none of the inputs/outputs have changed, the task will be automatically skipped and there should be a message similar to the one below:

```
> Task :private:apps:oauth:oauth-web:jar UP-TO-DATE
```

I did a quick spot check of the CI logs and saw those messages.  Are you seeing something different?

**Comment by holatuwol** [comment]
@petershin : The jar will usually be up-to-date, but we've been seeing the `npmInstall` and `classes` re-running as part of the `jar` up-to-date check, because we specifically disable that for patcher to make sure that everything is properly regenerated.

**Comment by holatuwol** [comment]
This is an example build log: https://test-1-20.liferay.com/job/fixpack-builder-hotfix-7x(production)/389/

**Comment by petershin** [comment]
@holatuwol - Ok. I think the better fix is to revert https://github.com/liferay/liferay-portal/commit/139ac282164dbc182533849ecdbb84fa49ff8577.  It's just masking the real problem.

Should I revert that commit so we can debug this issue or would it be better to keep things the same for now.

**Comment by holatuwol** [comment]
@petershin : No, we need to keep that commit, because we need to re-run `npmRunBuild` for the deploy step, but we don't need any NPM tasks during the `compileJSP` step.

**Comment by petershin** [comment]
Running additional tests here: https://github.com/petershin/liferay-portal/pull/605

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/76536

**Pull request closed without merging**
