### PR TITLE
LPS-100515

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
Hi @john-co, do any of the test failures look related to this pull?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

I think the tck-jdk8 test batch failure is a fluke but re-running test to verify.

**Comment by john-co** [comment]
**Comparison:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=891747721&testrayRunIdA=891616435&statusB=2

Functional test failures are flaky or fluke.

**Comment by john-co** [comment]
Hi @petershin, looks like the tck-jdk8 was indeed a fluke.

However, I now see some tests indicating a warning on com.liferay.trash.kernel.service.persistence requiring a version increase. Looks like gradle cache needs an update?

```
[exec] > Task :baseline3
[exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS
[exec] = ================================================== ========== ========== ========== ========== ==========
[exec] * com.liferay.trash.kernel.service.persistence       CHANGED    1.1.0      1.1.0      1.1.1      VERSION INCREASE REQUIRED
[exec] 	~   class      com.liferay.trash.kernel.service.persistence.TrashEntryUtil
[exec] 		-   annotated  aQute.bnd.annotation.ProviderType
[exec] 	~   class      com.liferay.trash.kernel.service.persistence.TrashVersionUtil
[exec] 		-   annotated  aQute.bnd.annotation.ProviderType
[exec] 	~   interface  com.liferay.trash.kernel.service.persistence.TrashEntryPersistence
[exec] 		-   annotated  aQute.bnd.annotation.ProviderType
[exec] 		+   annotated  org.osgi.annotation.versioning.ProviderType
[exec] 	~   interface  com.liferay.trash.kernel.service.persistence.TrashVersionPersistence
[exec] 		-   annotated  aQute.bnd.annotation.ProviderType
[exec] 		+   annotated  org.osgi.annotation.versioning.ProviderType
[exec] [Baseline Report] Mode: diff (persisted)
[exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/3.82.0/a43bc548b6e49ac0826d8754e45888d514c85ef1/com.liferay.portal.kernel-3.82.0.jar
```

**Comment by petershin** [comment]
Will take a look.  I likely can't push this up to master until next week due to issues in `7.0.x-private`

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/81414

**Pull request closed without merging**
