### PR TITLE
LPS-124343

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@gamerson - The CI failures are related to this change.

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:stop

**Pull request closed without merging**
