### PR TITLE
LPS-88645 CI suite

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@lawrence-lee - Do the `gradle-plugins-target-platform` failures look familiar to you?

**Comment by lawrence-lee** [comment]
@petershin, These don't ring a bell. I'm looking at the git history for `gradle-plugins-target-platform` would they have to do with the changes to gradle-plugins 9.0.0?

**Comment by petershin** [comment]
@lawrence-lee - It shouldn't.  Can you ask Greg if he recognizes the failures?

I want to resolve these issues so we can reliably use this test suite again.

**Comment by gamerson** [comment]
> @lawrence-lee - It shouldn't. Can you ask Greg if he recognizes the failures?
> 
> I want to resolve these issues so we can reliably use this test suite again.

Hey @petershin  I've sent a PR to fix the gradle tests here: https://github.com/petershin/liferay-portal/pull/1077

**Comment by petershin** [comment]
``

**Pull request closed without merging**
