### PR TITLE
LPS-98024 Add SF rules for YAML: Sort parameter types(in:path, in:query...)

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-98024

Hi @petershin,

Can you please review this pull?

Thanks.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
cc: @hhuijser

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failure is not in master branch.

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/76008

**Pull request closed without merging**
