### PR TITLE
LPS-0 Format Test

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf:norebase

**Comment by petershin** [comment]
ci:test:sf:norebase

**Comment by john-co** [comment]
maybe try removing your last commit TEST and rerun?

**Comment by petershin** [comment]
ci:reopen

**Comment by petershin** [comment]
@john-co - See https://github.com/petershin/liferay-portal/pull/636#issuecomment-521309953

hmm, the CI output is different again (doesn't match your pull or the one on this pull).  Is there someone in QA that can take a look at this and see what the issue is (maybe Peter Yoo)?

**Comment by john-co** [comment]
@petershin, I'm told that CII team doesn't have control over gradle tasks output specifically for SF related tasks.

@hhuijser, any ideas why the CI output for format source is different for these two pulls?

https://github.com/john-co/liferay-portal/pull/158/#issuecomment-521332445
https://github.com/petershin/liferay-portal/pull/637/#issuecomment-521335905

I sent the same commits, merged with master with the same conflict resolutions, and yet CI outputs don't match...

**Comment by hhuijser** [comment]
@john-co not sure, will look into that

**Pull request closed without merging**
