### PR TITLE
LPS-99047 Compile JSP

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Hi @john-co, do these failures look known issues?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
bundle-blacklist-restart-jdk8 looks unique, but I'm not sure if the error is related. rerunning test to see if it comes up again.

All other failures look unrelated.

**Comment by john-co** [comment]
bundle-blacklist-restart-jdk8

From 2 days ago:
```
junit.framework.AssertionFailedError: 
A bundle with the same symbolic name (com.liferay.portal.bundle.blacklist.test.bundle.war) and version (1.0.0) is already installed.  Updating this bundle instead. 
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:172)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
```

recent ci test result:
```
    [junit] 17:44:35,248 WARN  [main][LogService:99] Invocation of 'start' failed. 
    [junit] java.lang.Exception: Unable to start com.liferay.portal.tools.service.builder.test.service
    [junit] 	at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextRegistrator.start(ModuleApplicationContextRegistrator.java:112)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:498)
    [junit] 	at org.apache.felix.dm.InvocationUtil.invokeMethod(InvocationUtil.java:111)
    [junit] 	at org.apache.felix.dm.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:66)
    [junit] 	at org.apache.felix.dm.impl.ComponentImpl.invokeCallbackMethod(ComponentImpl.java:769)
    [junit] 	at org.apache.felix.dm.impl.ComponentImpl.invoke(ComponentImpl.java:760)
    [junit] 	at org.apache.felix.dm.impl.ComponentImpl.bindService(ComponentImpl.java:705)
    [junit] 	at org.apache.felix.dm.impl.ComponentImpl.access$400(ComponentImpl.java:54)
    [junit] 	at org.apache.felix.dm.impl.ComponentImpl$7.run(ComponentImpl.java:202)
    [junit] 	at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:137)
    [junit] 	at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:119)
    [junit] 	at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:85)
    [junit] 	at org.apache.felix.dm.impl.ComponentImpl.calculateStateChanges(ComponentImpl.java:252)
    [junit] 	at org.apache.felix.dm.impl.ComponentImpl.start(ComponentImpl.java:440)
    [junit] 	at org.apache.felix.dm.DependencyManager.add(DependencyManager.java:167)
    [junit] 	at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextExtender$ModuleApplicationContextExtension.start(ModuleApplicationContextExtender.java:150)
    [junit] 	at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextExtender.addingBundle(ModuleApplicationContextExtender.java:76)
    [junit] 	at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextExtender.addingBundle(ModuleApplicationContextExtender.java:55)
    [junit] 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
    [junit] 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
    [junit] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
    [junit] 	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
    [junit] 	at org.osgi.util.tracker.BundleTracker.open(BundleTracker.java:159)
    [junit] 	at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextExtender.activate(ModuleApplicationContextExtender.java:246)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:498)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307)
    [junit] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:341)
    [junit] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114)
    [junit] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:983)
    [junit] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:956)
    [junit] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765)
    [junit] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053)
    [junit] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007)
    [junit] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216)
    [junit] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137)
    [junit] 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:944)
    [junit] 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:880)
    [junit] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1168)
    [junit] 	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125)
    [junit] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
    [junit] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891)
    [junit] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
    [junit] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
    [junit] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
    [junit] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469)
    [junit] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:487)
    [junit] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:1004)
    [junit] 	at com.liferay.registry.internal.RegistryImpl.registerService(RegistryImpl.java:374)
    [junit] 	at com.liferay.portal.internal.servlet.MainServlet._registerPortalInitialized(MainServlet.java:1273)
    [junit] 	at com.liferay.portal.internal.servlet.MainServlet.init(MainServlet.java:449)
    [junit] 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
    [junit] 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1123)
    [junit] 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1078)
    [junit] 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:971)
    [junit] 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4868)
    [junit] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5184)
    [junit] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    [junit] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:713)
    [junit] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
    [junit] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
    [junit] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
    [junit] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1832)
    [junit] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
    [junit] 	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
    [junit] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
    [junit] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1577)
    [junit] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
    [junit] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
    [junit] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
    [junit] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
    [junit] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:929)
    [junit] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:831)
    [junit] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    [junit] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
    [junit] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    [junit] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
    [junit] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
    [junit] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    [junit] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:423)
    [junit] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    [junit] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:928)
    [junit] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    [junit] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:634)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:498)
    [junit] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
    [junit] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
    [junit] Caused by: java.util.ConcurrentModificationException
    [junit] 	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
    [junit] 	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
    [junit] 	at org.apache.commons.configuration.CompositeConfiguration.getList(CompositeConfiguration.java:350)
    [junit] 	at org.apache.commons.configuration.AbstractConfiguration.getList(AbstractConfiguration.java:1117)
    [junit] 	at com.liferay.portal.configuration.ClassLoaderAggregateProperties.getProperties(ClassLoaderAggregateProperties.java:84)
    [junit] 	at com.liferay.portal.configuration.ConfigurationImpl.getProperties(ConfigurationImpl.java:272)
    [junit] 	at com.liferay.portal.util.PropsUtil.getProperties(PropsUtil.java:154)
    [junit] 	at com.liferay.portal.util.PropsUtil.getProperties(PropsUtil.java:148)
    [junit] 	at com.liferay.portal.spring.hibernate.PortalHibernateConfiguration.newConfiguration(PortalHibernateConfiguration.java:133)
    [junit] 	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:507)
    [junit] 	at com.liferay.portal.spring.hibernate.PortalHibernateConfiguration.buildSessionFactory(PortalHibernateConfiguration.java:85)
    [junit] 	at com.liferay.portal.spring.aop.AopConfigurableApplicationContextConfigurator$AopBeanFactoryPostProcessor._getPlatformTransactionManager(AopConfigurableApplicationContextConfigurator.java:208)
    [junit] 	at com.liferay.portal.spring.aop.AopConfigurableApplicationContextConfigurator$AopBeanFactoryPostProcessor.postProcessBeanFactory(AopConfigurableApplicationContextConfigurator.java:122)
    [junit] 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:283)
    [junit] 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:128)
    [junit] 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
    [junit] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
    [junit] 	at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextRegistrator.start(ModuleApplicationContextRegistrator.java:94)
    [junit] 	... 105 more
```

@vicnate5 have you seen this before?

**Comment by vicnate5** [comment]
The first error is https://issues.liferay.com/browse/LPS-97673

The second I have not seen before, where is that occurring?

**Comment by john-co** [comment]
@vicnate5 the 2nd error occurs on when starting up the bundle. 

https://gist.github.com/john-co/5342955f4f650a61bdaf9958ddaaef5a

**Comment by vicnate5** [comment]
@john-co possible intermittent issues. I do not see any other examples of the `Unable to start com.liferay.portal.tools.service.builder.test.service` in this pull or others. Running a smaller group of tests again, but this does not look related to the PR @petershin

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by vicnate5** [comment]
bundle blacklist test passed on new run

**Comment by petershin** [comment]
Sent to Brian: brianchandotcom#76536

**Pull request closed without merging**
