### PR TITLE
LPS-109810

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85861

**Comment by BryanEngler** [comment]
hey @petershin if its possible to give this some priority we wanted to have it for the 7.2 SP2 release, which i heard could be built by end of day tomorrow, but no worries if you cant resolve it by then. thanks!

**Comment by petershin** [comment]
@BryanEngler - Taking a look

**Comment by petershin** [comment]
@BryanEngler - I think Brian just needs to install an executable on his machine

The patch task worked for me.  Is it working for you?

**Comment by petershin** [comment]
Followed up w Bryan on slack and provided steps to run the command.

**Pull request closed without merging**
