### PR TITLE
LPS-112052

### PR DESCRIPTION
**Pull request by petershin**
@david-truong

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by david-truong** [comment]
@gamerson

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
Hi @pyoo47, there's no unique failures for this pull.  Is it ok to manually send this to bchan?

**Comment by john-co** [comment]
ci:forward

**Comment by pyoo47** [comment]
@petershin - At this point, you could probably send it manually to BChan. I'm not really the one who decides such things but he has mentioned to me that he's OK with pull requests that don't have any unique failures. Currently, our ci:forward feature doesn't forward in that case.

**Comment by petershin** [comment]
@pyoo47 - Ok, I'll remember that for next time.  John Co wanted to run `ci:forward` again for this pull

**Comment by john-co** [comment]
@petershin, looks like a rebase issue.

**Comment by petershin** [comment]
Rebased and sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/87790

**Pull request closed without merging**
