### PR TITLE
LPS-102797 Logging

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
Hi @john-co, are these failures known issues?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
These functional test failures look unique to the PR:
**Elasticsearch6#ElasticsearchRemoteClusterSmokeTest**
https://testray.liferay.com/home/-/testray/case_results/822682307

Possible fluke? **DisplayPageTemplatesWithFragmentConfiguration#AddTextConfigurationFragmentToDisplayPageTemplate**
https://testray.liferay.com/home/-/testray/case_results/822624805

Possible fluke? **TagsUseCase#ViewTagCloudIncrease**
https://testray.liferay.com/home/-/testray/case_results/822730005

Investigating further, may need to wait for the last test run to finish and compare results.

**Comment by john-co** [comment]
Reviewed. Functional test failures are not related. Will double check backend test batches.

The CI results from this morning show that the tests are passing. Most likely flukes. https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=824535473&testrayRunIdA=822593066&statusB=2

**Comment by petershin** [comment]
@john-co - Appreciate the review!  Will wait for your final ok before sending to upstream

**Comment by john-co** [comment]
**bundle-blacklist-restart-jdk8** test failure looks unique but I'm not sure if it's related to the pull or a fluke:

```
  [junit] Testcase: testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] A bundle with the same symbolic name (com.liferay.portal.bundle.blacklist.test.bundle.war) and version (1.0.0) is already installed.  Updating this bundle instead. 
    [junit] junit.framework.AssertionFailedError: 
    [junit] A bundle with the same symbolic name (com.liferay.portal.bundle.blacklist.test.bundle.war) and version (1.0.0) is already installed.  Updating this bundle instead. 
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:172)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
    [junit] 
    [junit] 
```

**Comment by john-co** [comment]
bundle-blacklist-restart-jdk8 is an existing issue: https://issues.liferay.com/browse/LPS-97673

PR looks good! :tada: :heavy_check_mark:

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/79423

**Pull request closed without merging**
