### PR TITLE
LPS-78854 Clean up SF list

### PR DESCRIPTION
**Pull request by mtambara**
cc @shuyangzhou

Hi Peter, this pull removes some of the exceptions from BNDExportsCheck for master. As I understand, this should be the only change needed since [source-formatter.properties](https://github.com/liferay/liferay-portal-ee/blob/7.0.x/source-formatter.properties) in 7.0.x has the `override.bnd.exports.check.allowed.export.package.dir.name` property already, correct?

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by petershin** [comment]
There's a 7.1.x branch and the source-formatter.properties file may need to be updated there as well

**Comment by petershin** [comment]
The 7.1.x looks ok.  Sent the changes to Brian: https://github.com/brianchandotcom/liferay-portal/pull/56444

**Comment by petershin** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/56585

**Pull request closed without merging**
