### PR TITLE
LPS-109953 Avoid exceeding 120 characters for description

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Peter,

See: https://github.com/brianchandotcom/liferay-portal/pull/87737

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by petershin** [comment]
Forwarding to Brian: https://github.com/petershin/liferay-portal/pull/978

**Pull request closed without merging**
