### PR TITLE
LPD-15162 Gradle 8.5

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:stable

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:stable

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:test:stable

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:relevant:norebase

**Comment by bryceosterhaus** [comment]
ci:report:2547498338

**Comment by bryceosterhaus** [comment]
ci:stop

**Comment by bryceosterhaus** [comment]
ci:report:2547926769

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:report:2548796476

**Comment by vicnate5** [comment]
ci:report:2548796476

**Comment by petershin** [comment]
ci:test:gradle-plugins:norebase

**Comment by petershin** [comment]
ci:test:sf:norebase

**Comment by petershin** [comment]
ci:report:2549890576

**Pull request closed without merging**
