### PR TITLE
LPS-100281 replace project dependencies with snapshots

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by petershin** [comment]
@david-truong - Will this plugin only be used on liferay-portal `master`?

**Comment by david-truong** [comment]
Initially.  I'm going to get feedback on it before I add support for master-private

**Comment by petershin** [comment]
@david-truong - ah ok

just fyi, I'm thinking about moving the logic from the binaries into a `Gradle` build script to follow the existing pattern

**Comment by david-truong** [comment]
Sure I was thinking we would combine this into an existing plugin like the defaults one anyways

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/77866

**Pull request closed without merging**
