### PR TITLE
LPS-97550 Arquillian

### PR DESCRIPTION
**Pull request by petershin**
@gamerson

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
Thanks @petershin  for the review

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Fixed at least a couple of the errors here: https://github.com/petershin/liferay-portal/pull/562 

I'm not sure why the FileUtil.getJavaClassesDir method is failing, maybe a bad fake cache?

**Pull request closed without merging**
