### PR TITLE
LPS-101947 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by petershin** [comment]
@hhuijser - the `gradle-test` suite had the same failure in this pull

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@gamerson - this looks good.  I'm holding off on sending any Gradle changes until the SP is released

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/78949

**Pull request closed without merging**
