### PR TITLE
LPS-95442 fix arquillian tests regression

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
ci:stop (need to regen)

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:test

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/73187

**Pull request closed without merging**
