### PR TITLE
LPS-99895 Update project-templates

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
@petershin, the gradle plugins error looks the same. 
Can you send the project templates failure back to me? Its just a version mismatch with workspace.

**Comment by petershin** [comment]
@lawrence-lee - Sent you a pull: https://github.com/lawrence-lee/liferay-portal/pull/127

My commits are to fix the failures in `ci:test:gradle-plugins`. Will send that fix to bchan in a separate pull if the tests pass.  See https://github.com/petershin/liferay-portal/pull/663

**Pull request closed without merging**
