### PR TITLE
LPS-181508 Dev Tools

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:stable:norebase

**Comment by petershin** [comment]
ci:test:gradle-plugins:norebase

**Comment by simonjhy** [comment]
@petershin here is local build scan result https://scans.gradle.com/s/5fdjqtvfzours/console-log?anchor=111&page=1.

**Comment by simonjhy** [comment]
ci:test:gradle-plugins:norebase

**Comment by simonjhy** [comment]
ci:test:gradle-plugins:norebase

**Comment by simonjhy** [comment]
ci:test:gradle-plugins:norebase

**Pull request closed without merging**
