### PR TITLE
LPS-105747 Changelogs - Add description section

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
cc @hhuijser

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by petershin** [comment]
@ling-alan-huang - These changes caused a few dates to be missing from the `gradle-plugins-source-formatter` changelog.

I reverted the bad commit, but that caused a different issue.  Please see the last generated commit in the latest pull: https://github.com/ling-alan-huang/liferay-portal/pull/166

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/petershin/liferay-portal/pull/846

**Pull request closed without merging**
