### PR TITLE
LPS-127801 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**
Hi @brianchandotcom, please publish `gradle-plugins-theme-builder` then `gradle-plugins-workspace` then `project-templates-*`.

Thanks!

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Pull request closed without merging**
