### PR TITLE
LPS-93873 changelog

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
hey @petershin  could you ask BChan to publish new builds
`gradle-plugins-target-platform`
`gradle-plugins-workspace`

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/71601

**Pull request closed without merging**
