### PR TITLE
LPS-148033 form filed project should to update node_modules

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
@petershin I checked the project template test issue, its related to portal-kernel.jar not our project template.

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
https://github.com/petershin/liferay-portal/pull/1613

**Pull request closed without merging**
