### PR TITLE
LPS-182369 Add snakeyaml dependency to settings.gradle temporally

### PR DESCRIPTION
**Pull request by Seiphon**
Hey @petershin , I need to add snakeyaml dependency to settings.gradle of workspace to fix the issue thatUTF-8 characters are not allowed. And this will be a temporally fix, we will clean up the dependencies in few tickets later.

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
Fwding to bchan: https://github.com/petershin/liferay-portal/pull/2041

**Pull request closed without merging**
