### PR TITLE
LPS-77897 integrate docker with liferay-workspace

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by petershin** [comment]
@david-truong - Some of the new tasks are simple and seem like they can be used in the other subrepos.  If the changes below make sense, can you implement them in this pull:

- update the `build.gradle` in `gradle-plugins-workspace` to use `com.liferay.gradle.plugins.app.docker`
- move the tasks `startDocker`, `stopDocker`, `logsContainer` to `com.liferay.gradle.plugins.app.docker` 
- please rename the tasks to match the existing task names and use generic defaults
- create `gradleTest` and update the `readme`

**Comment by david-truong** [comment]
I chose not to use app docker plugin because it added alot of things I didn't need without providing me anything useful

**Comment by david-truong** [comment]
rebased to master and also updated the change log

**Comment by petershin** [comment]
https://github.com/david-truong/liferay-portal/pull/108

**Pull request closed without merging**
