### PR TITLE
POSHI-607 Update for chromedriver 115+

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-607

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
will close, resend, and reforward due to the merge conflicts. Thanks for looking it over @petershin !

**Comment by kenjiheigel** [comment]
Resent here: 
https://github.com/kenjiheigel/liferay-portal/pull/1433

**Pull request closed without merging**
