### PR TITLE
LPS-159736 Add docker documentation 

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by Seiphon** [comment]
ci:forward

**Comment by Seiphon** [comment]
since there are some conflicts with master, I will rebase to latest master and resolve these conflicts manully, then I will resend the pr

**Comment by Seiphon** [comment]
have resent the pr here https://github.com/petershin/liferay-portal/pull/1773

**Pull request closed without merging**
