### PR TITLE
LPS-129870

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:stable

**Comment by petershin** [comment]
ci:test:stable

**Comment by petershin** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
Also running test here:
https://github.com/yichenroy/liferay-portal/pull/618

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:forward

**Pull request closed without merging**
