### PR TITLE
lps-99895

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
resent: https://github.com/petershin/liferay-portal/pull/661

**Pull request closed without merging**
