### PR TITLE
LPS-86018 add test for installed an exploded portlet war as a directory

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test

**Comment by gamerson** [comment]
hey @petershin  I fixed the test failure and also added a new test

**Comment by gamerson** [comment]
@petershin  seems to be ok.

**Comment by gamerson** [comment]
@petershin  fixed

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/64296

**Pull request closed without merging**
