### PR TITLE
Lps 134302 2

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
Tests passed here: https://github.com/gamerson/liferay-portal/pull/523

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:reevaluate:1127401_4891

**Comment by petershin** [comment]
ci:reevaluate:1127401_4891

**Comment by petershin** [comment]
ci:forward

**Pull request closed without merging**
