### PR TITLE
LPS-86544 use latest

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
Hi @gamerson, there are conflicts with Lawrence's pull: https://github.com/brianchandotcom/liferay-portal/pull/65177

Please rebase after his pull is merged and use the commit pattern below. It'll help speed up the review process for future pulls. If you see any issues with this approach, we can adjust the pattern.

- All manual changes go first
- `LPS-XXX Update project template tokens` (`build.gradle` `ext.projectTemplateTokens` changes)
- `LPS-XXX Use latest project-templates` (auto-generated changes only - if `gw installCache updateFileVersions` is run multiple times, each time its run should be a separate commit)
- `LPS-XXX FAKE GRADLE CACHE` (m2-tmp jars)

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
resent here: https://github.com/petershin/liferay-portal/pull/305

**Pull request closed without merging**
