### PR TITLE
LRCI-2670 Add poshi-standalone

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:reevaluate:1257401_1181

**Comment by petershin** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:reevaluate:1277401_1248

**Comment by kenjiheigel** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:forward

**Pull request closed without merging**
