### PR TITLE
LPS-142340 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**
Please publish `gradle-plugins-workspace`, then `project-templates-extensions`, then `project-templates-*`

### CODE REVIEW

**Comment by lawrence-lee** [comment]
Tests passed here: https://github.com/lawrence-lee/liferay-portal/pull/239#issuecomment-967201488

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
@Seiphon Tests are failing. Can you resend?

**Comment by Seiphon** [comment]
> @Seiphon Tests are failing. Can you resend?

Hi @lawrence-lee , I have resent the pr to you here https://github.com/lawrence-lee/liferay-portal/pull/242, and all the tests are passed

**Pull request closed without merging**
