### PR TITLE
SF on master | needs LPS

### PR DESCRIPTION
**Pull request by jpince**
@petershin ran  at master head just for fun and was surprised to see a bunch of changes. can you please assign LPS numbers for these commits? (I'm assuming they're related to SF tool changes) Also not sure why SF passed after writing these changes?

### CODE REVIEW

**Comment by jpince** [comment]
also, saw these lines at the top of the log. I think, however, these should be allowed. impl should be able to be titled as "Implementation", util as "Utilities", etc.
```
     [java] Incorrect Bundle-Name 'Liferay Adaptive Media Image Implementation Test', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/bnd_bundle_information.markdown: ./modules/apps/adaptive-media/adaptive-media-image-impl-test/bnd.bnd (SourceCheck:BNDBundleInformationCheck)
     [java] Incorrect Bundle-Name 'Liferay Frontend Taglib Utilities FreeMarker Contributor', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/bnd_bundle_information.markdown: ./modules/apps/frontend-taglib/frontend-taglib-util-freemarker-contributor/bnd.bnd (SourceCheck:BNDBundleInformationCheck)
     [java] Incorrect Bundle-Name 'Liferay Portal Configuration Test Utilities Test', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/bnd_bundle_information.markdown: ./modules/apps/portal-configuration/portal-configuration-test-util-test/bnd.bnd (SourceCheck:BNDBundleInformationCheck)
     [java] Incorrect Bundle-Name 'Liferay Portal Kernel Utilities Compat', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/bnd_bundle_information.markdown: ./modules/core/portal-compat/petra/portal-kernel-util-compat/bnd.bnd (SourceCheck:BNDBundleInformationCheck)
     [java] Incorrect Bundle-Name 'Liferay Utilities Java Compat', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/bnd_bundle_information.markdown: ./modules/core/portal-compat/petra/util-java-compat/bnd.bnd (SourceCheck:BNDBundleInformationCheck)
     [java] Incorrect Bundle-Name 'Liferay Utilities Taglib Compat', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/bnd_bundle_information.markdown: ./modules/core/util-taglib-compat/bnd.bnd (SourceCheck:BNDBundleInformationCheck)
```

**Comment by jpince** [comment]
ci:test:sf

**Comment by petershin** [comment]
@jpince - Try running the command below.  This should result in no changes


```
portal-impl: ant format-source-all '-Dskip.npm=true'
```

**Comment by petershin** [comment]
The `bnd` errors have been fixed by this [commit](https://github.com/liferay/liferay-portal/commit/0393cc4b8d47bd1a1467c82046967de837b8e1e7#diff-d78ab7ff358df7f79f3b90b8bce9c364)

It'll be fixed when a new version of the SF is released (usually happens once a day)

**Comment by petershin** [comment]
https://github.com/petershin/liferay-portal/pull/148

**Pull request closed without merging**
