### PR TITLE
LPS-150769 add another productinfo backup url

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
https://github.com/petershin/liferay-portal/pull/1676

**Pull request closed without merging**
