### PR TITLE
LPS-143719 publish new gradle workspace plugin

### PR DESCRIPTION
**Pull request by simonjhy**
Hi Brian, please publish a new version of gradle-plugins-workspace. There is a fix that was added for 7.4. See bfe5da1c

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
Forwarding to Brian: https://github.com/petershin/liferay-portal/pull/1553

**Pull request closed without merging**
