### PR TITLE
LPS-173738 Upgrade sass-embedded-host version to 2.1.0

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by petershin** [comment]
@Seiphon - There are compile errors. Run `gw :util:sass-compiler-dart:compileJava`

**Comment by petershin** [comment]
ci:stop

**Comment by Seiphon** [comment]
OK, I will fix the errors and resend the pr

**Pull request closed without merging**
