### PR TITLE
LPS-152267 remove soy dependency for portal 7.4 form-field template

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
@petershin here is the test result. https://github.com/simonjhy/liferay-portal/pull/67

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:reevaluate:1277401_4281

**Comment by petershin** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:reevaluate:1387401_2720

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:reevaluate:1257401_3993

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
Manually forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/121461

**Pull request closed without merging**
