### PR TITLE
LPS-105747 Changlogs

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
cc @hhuijser

**Comment by petershin** [comment]
Hi @ling-alan-huang, the `### Dependencies` section for `gradle-plugins` also needs to include changes from [portal-tools.properties](https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins/src/main/resources/com/liferay/gradle/plugins/dependencies/portal-tools.properties).

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
Hi @petershin, I made some changes to get dependencies for `gradle-plugins`.

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/84865

**Pull request closed without merging**
