### PR TITLE
LPS-114546 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
cc @gamerson

**Comment by petershin** [comment]
Forwarding to Brian: https://github.com/petershin/liferay-portal/pull/1016

**Pull request closed without merging**
