### PR TITLE
LPS-173738 Seiphon

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:stable

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by Seiphon** [comment]
ci:test:stable

**Comment by Seiphon** [comment]
ci:test:gradle-plugins

**Comment by Seiphon** [comment]
ci:test:gradle-plugins

**Comment by Seiphon** [comment]
Hi @petershin , I have tried ro gradleTest on local, it also failed with `org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':apps:java-theme'.` error. It seems we also need generate the caches for java-theme project

**Comment by petershin** [comment]
@Seiphon - the repositories closure for `gradleTest` projects likely needs to be updated to include the `.m2-tmp` directory. see [baz-theme/build.gradle#L9](https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins-workspace/src/gradleTest/themesJavaBuild/themes/baz-theme/build.gradle#L9)

the test will likely be ok after bchan publishes. the stable test suite passed, so forwarding this manually to bchan

**Comment by petershin** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/130206

**Pull request closed without merging**
