### PR TITLE
LPS-92581

### PR DESCRIPTION
**Pull request by lawrence-lee**
cc @anthony-chu

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci: stop

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:relevant:norebase

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/73132

**Pull request closed without merging**
