### PR TITLE
LPS-85765 Add packageinfo files

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@petershin, this looks like a known issue that could be fixed by https://issues.liferay.com/browse/LPS-112137. Rerunning the tests.

**Comment by john-co** [comment]
May want to check on the modules-unit-project-templates-jdk8 test. Latest upstream test is still running: https://test-1-14.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=0,label_exp=!master/52812/console

**Comment by petershin** [comment]
This pull just exports a few classes, so it should be ok.  Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/87791

**Pull request closed without merging**
