### PR TITLE
LPS-98937 exportimport taglib compileJSP fix

### PR DESCRIPTION
**Pull request by gamerson**
LPS-98937 exportimport taglib compileJSP fix

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by petershin** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76787

**Comment by petershin** [comment]
Sent to Brian: See https://github.com/brianchandotcom/liferay-portal/pull/76816

**Pull request closed without merging**
