### PR TITLE
LPS-121567

### PR DESCRIPTION
**Pull request by petershin**
@wincent

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:foward

**Comment by petershin** [comment]
ci:stop

**Comment by wincent** [comment]
My understanding of why this failed:

- [This line in build.gradle](https://github.com/liferay/liferay-portal/blob/021b09a2df5e71140dd6061497000db108f09048/modules/apps/frontend-editor/frontend-editor-ckeditor-web/build.gradle#L53) blows up because `packageRunBuild.destinationDir` is `null` instead of a string.
- It's `null` because [the setter](https://github.com/liferay/liferay-portal/blob/021b09a2df5e71140dd6061497000db108f09048/modules/sdk/gradle-plugins-node/src/main/java/com/liferay/gradle/plugins/node/tasks/PackageRunBuildTask.java#L129-L131) never gets called.
- It's supposed to get called [from here](https://github.com/liferay/liferay-portal/blob/d2d24f4883781d8f976baa499ca2f70bb2b3bb41/modules/sdk/gradle-plugins-node/src/main/java/com/liferay/gradle/plugins/node/NodePlugin.java#L717-L725).
- I figured (incorrectly, maybe?) that [the `_hasLiferayNpmScripts12Dependency()`](https://github.com/liferay/liferay-portal/blob/d2d24f4883781d8f976baa499ca2f70bb2b3bb41/modules/sdk/gradle-plugins-node/src/main/java/com/liferay/gradle/plugins/node/NodePlugin.java#L1015-L1019) check returning `false` was causing us to skip the set-up, so I made the change to the plugin to detect `@liferay/npm-scripts` as well.
- But we still see things blowing up, which makes me think that [this conditional](https://github.com/liferay/liferay-portal/blob/d2d24f4883781d8f976baa499ca2f70bb2b3bb41/modules/sdk/gradle-plugins-node/src/main/java/com/liferay/gradle/plugins/node/NodePlugin.java#L711-L712) is still not passing even with my change.

**Comment by petershin** [comment]
@wincent - I made a minor fix and will rerun the test

**Comment by petershin** [comment]
Resent: https://github.com/petershin/liferay-portal/pull/1215

**Pull request closed without merging**
