### PR TITLE
LPS-104540 Athanasius

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:gradle-plugins:norebase

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
Hi @john-co, do any of the test failures look related to this pull?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Hi @petershin,
The test failure on [SampleProjectTemplates#ThemeTemplateSmoke](https://testray.liferay.com/home/-/testray/case_results/880003497) looks related, the same issue occurs in https://github.com/petershin/liferay-portal/pull/793 and https://github.com/petershin/liferay-portal/pull/795

**Testray error log:**
`java.lang.Exception: "sampletheme" is not present`

It looks like the sampleTheme isn't compatible for 7.3.10 [jenkins log](https://testray.liferay.com/reports/production/logs/test-1-18/1573795082731/test-portal-acceptance-pullrequest(master)/2421/functional-tomcat90-mysql57-jdk8/70/0/jenkins-console.txt.gz)
 
**Jenkins error log snippet:**
```
     [exec] 09:47:28,275 INFO  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/war][BaseAutoDeployListener:43] Copying themes for /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.17/temp/20191115094728271FIELKQRJ/sampletheme.war
     [exec] 09:47:28,311 INFO  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/war][BaseDeployer:871] Deploying sampletheme.war
     [exec] 09:47:28,810 INFO  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/war][BaseAutoDeployListener:50] Themes for /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.17/temp/20191115094728271FIELKQRJ/sampletheme.war copied successfully
     [exec] 09:47:29,019 INFO  [main][SystemCheckOSGiCommands:126] Declarative Service Soft Circular Dependency Checker check result: No issues were found.
     [exec] 09:47:29,020 INFO  [main][SystemCheckOSGiCommands:114] Running "Declarative Service Unsatisfied Component Checker". You can run this by itself with command "ds:unsatisfied" in gogo shell.
     [exec] 09:47:29,638 ERROR [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/war][ThemeLocalServiceImpl:606] Themes in this WAR are not compatible with Liferay Digital Experience Platform / 7.3.10
     [exec] 09:47:29,638 INFO  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/war][ThemeHotDeployListener:113] 0 themes for sampletheme are available for use
     [exec] 09:47:29,694 INFO  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/war][BundleStartStopLogger:39] STARTED sampletheme_1.0.0 [1033]
```
All other functional test failures look unrelated.

**Comment by petershin** [comment]
@john-co - taking a look

**Comment by petershin** [comment]
@john-co - Lawrence Lee will add a fix for that issue, so I've temporarily disabled that test

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/81037

**Pull request closed without merging**
