### PR TITLE
LPS-105747 Changelogs

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Peter,

**Change 1:** [LPS-105747 Manual, reverse the order, latest to earliest](https://github.com/petershin/liferay-portal/commit/de593dfa800b1ddeb042ee6b32722b91fa6d5f33)

**Change 2:** [LPS-105747 Filter out the commits that don't provide useful information](https://github.com/petershin/liferay-portal/commit/82d8c18b4f75eadb5edbc179da34dbf1984b9550), see it's results on CHANGELOG.markdown: https://github.com/petershin/liferay-portal/commit/a06606568abc22b733f27f50d9da51437c727b6f

**Change 3:** [LPS-105747 Avoid SF error](https://github.com/petershin/liferay-portal/commit/49a483c7f42631358175703ebe65eb760f55a62b), because 6659d6f32b has no additional information, just the ticket number. See this changes on CHANGELOG.markdown: https://github.com/petershin/liferay-portal/pull/851/commits/ec4769e8eabcefaf13425a6c09327b306c9d87b3

-------------

For commits section, tomorrow I will grab all changes in directory(modules/sdk/${projectName}),
and I will add logic to filter out the commits that don't provide useful information.

_For example:_

1.0.4 gradle-plugins-alloy-taglib 
(17e1f73fda46ea3331afd21ad31141ee50fb3a64..3bf6a2f254e719238a66fa40dc51281fd116507c),

(Not useful) 3bf6a2f254e719238a66fa40dc51281fd116507c LPS-67573 Semver gradle-plugins-alloy-taglib
(Not useful) 72a985ef36421c4a6e06ab28c858ea6afcf0bb71 LPS-67573 Enable semver check for gradle-plugins-alloy-taglib
(Useful)     0355d2a43d4521646e205291eb703845ae7e251a LPS-67573 Remove unused method
(Useful)     ac537a9812962b7d07aca94aadab696f67618ee2 LPS-67573 Make methods private to reduce API surface
(Not useful) 4a3cd0bc9de25abe1196c321f60d0fe01e2b56b5 LPS-67658 Need "compileOnly" to keep dependencies out of "compile"
(Not useful) 5b963e363ddd4b8e6a35c212192d27b67d31e40e LPS-67658 These plugins must work with Gradle 2.5+
(Not useful) 17e1f73fda46ea3331afd21ad31141ee50fb3a64 LPS-65749 prep next, use latest

But I think it is difficult to remove usefulness commit by commit message. Do you have any good idea?

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
cc @hhuijser

**Comment by petershin** [comment]
@ling-alan-huang - I removed the commit that filtered out commits b/c it removed messages that were helpful

```
- [LPS-67658]: These plugins must work with Gradle 2.5+ (5b963e363d)
```

Lets ignore just the commits that are documented in the descriptions section along w the prep next commits for now.  None of the changelogs need to be regenerated in the next pull.

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/82969

**Pull request closed without merging**
