### PR TITLE
LPS-108328

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-108328

In testing, the `[0-9.]*` seemed unnecessary. Do you remember why you made that change?

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Hi Minhchau, I'll create the backport pulls before sending to Brian.

I modified these files awhile back when we updated the `bnd` library.  Their regex parser changed and it broke the `jar` task.

I didn't modify the existing pattern (just fixed it).  This change seems fine to me.

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/85774

**Pull request closed without merging**
