### PR TITLE
LPS-101026 Remove Gradle task formatXML

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Peter, @hhuijser,

https://issues.liferay.com/browse/LPS-101026

one more thing:
I searched for `com.liferay.xml.formatter`, these two folder/file are ignored by `.gitignore`.
`liferay-portal/tools/sdk/dependencies/com.liferay.xml.formatter`
`liferay-portal/tools/sdk/build-common-plugin.xml`

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@ling-alan-huang - Nice!

A new service pack is in the process of being released.  Will send this to bchan in a day or two.

**Comment by petershin** [comment]
ci:test:bundle:norebase

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/78954

**Pull request closed without merging**
