### PR TITLE
LPS-93350 Recursively deploying demo-data-creator dependencies

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/71027

@4lejandrito - I moved the configuration logic to the deploy task.

After its merged to upstream, please test to see if it works as expected.

**Pull request closed without merging**
