### PR TITLE
LPS-160184 JSP bnd plugin should not add Imports for Classes

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
@petershin here is test result https://github.com/simonjhy/liferay-portal/pull/94.

**Comment by petershin** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
@petershin I posted a message in slack CI channel about this pull failure.

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
@simonjhy - The `ci:test:sf` failure can be ignored. It's checking everything bc `source-formatter.properties` was changed

**Comment by simonjhy** [comment]
ci:forward

**Comment by petershin** [comment]
ci:test:relevant

**Pull request closed without merging**
