### PR TITLE
lps-87417

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
@petershin do you know what this error is?

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
@lawrence-lee - Will send a followup pull and cc you on it.

**Comment by petershin** [comment]
See https://github.com/petershin/liferay-portal/pull/290

**Pull request closed without merging**
