### PR TITLE
LPS-154340 Make buildREST and buildService less strict

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by petershin** [comment]
@simonjhy - Can you move the logic to workspace, so that the appropriate `xxx-builder` plugin is applied only if that file exists in the project's root directory? This will make the build slightly faster.

**Comment by simonjhy** [comment]
OK，will do it today, thanks peter.

**Pull request closed without merging**
