### PR TITLE
LPS-90120 Add Company as a parameter to every method.

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @petershin,

We need to add a CompanyProvider so the Company is provided for the API method.

Thanks in advance.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/67615

**Pull request closed without merging**
