### PR TITLE
LPS-111291 Gradle 6.6.1

### PR DESCRIPTION
**Pull request by petershin**
https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest(master)/485/

### CODE REVIEW

**Comment by petershin** [comment]
@yichenroy - The link below doesn't work anymore.  Can you provision a new CI server with double the memory like before?

 https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest(master)/464/

**Comment by yichenroy** [comment]
@petershin got it, I'll prepare one and link here

**Comment by yichenroy** [comment]
@petershin test-1-24 is under some load, I queued up a new build for this pr as `#485` on here:
https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest(master)/

Once the build gets off the queue and starts you'll be able to click in and perform rebuild or other actions.

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
https://github.com/petershin/liferay-portal/pull/1230

**Pull request closed without merging**
