### PR TITLE
LPS-162545 Add Postaction for liferay maven workspace project template

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
Here is the test result(https://github.com/simonjhy/liferay-portal/pull/74)

**Comment by petershin** [comment]
`WorkspaceProjectTemplateCustomizer.java` and `archetype-post-generate.groovy` are very similar

Can we just have one of them and use it everywhere?

**Comment by simonjhy** [comment]
the WorkspaceProjectTemplateCustomizer is used for liferay blade projec template. the archetype-post-generate.groovy is used to pure maven archetype. The groovy script can not find the class we define in other place. It also has some special requirements. Like the groovy script's classes or methods with no visibility modifier are automatically public (a special annotation can be used to achieve package private visibility). The groovy can not have global static variable. So I have to separately defined them.

**Comment by gamerson** [comment]
> `WorkspaceProjectTemplateCustomizer.java` and `archetype-post-generate.groovy` are very similar
> 
> Can we just have one of them and use it everywhere?

Hey Peter, 

When you invoke `blade create` it doesn't execute the archetype-post-generate.groovy because of the maven-archteyper framework doesn't include support for that.

When a user invokes `mvn archetype:generate` it doesn't run our `ProjectTemplateCustomizers` because it doesn't know anything about those.  So we have to duplicate the logic if we want to support both `blade create` and `mvn archetype:generate` use-cases.

**Comment by gamerson** [comment]
hey @petershin  I spoke with Simon about the plan to refactor ProductInfo and Bundle URL Codec so this can be closed.

**Comment by simonjhy** [comment]
thanks peter, greg.

**Pull request closed without merging**
