### PR TITLE
LPS-100515 Gradle 5.6.4

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
Hi @john-co, do any of the test failures look related to this pull?

**Comment by petershin** [comment]
ci:test:project-templates

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
**Looks related?:**

- [SampleProjectTemplates#WarMvcPortletTemplateSmoke](https://testray.liferay.com/home/-/testray/case_results/882673928)

```
    [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] Project directory '/opt/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates-war-mvc-portlet/build/samplewarmvcportlet' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.InvalidUserDataException: Project directory '/opt/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates-war-mvc-portlet/build/samplewarmvcportlet' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 	at org.gradle.initialization.AbstractProjectSpec.selectProject(AbstractProjectSpec.java:42)
     [exec] 	at org.gradle.initialization.DefaultSettingsLoader.setDefaultProject(DefaultSettingsLoader.java:88)
     [exec] 	at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:52)
```

- [SampleProjectTemplates#RestTemplateSmoke](https://testray.liferay.com/home/-/testray/case_results/882673368)

```
     [exec] * What went wrong:
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates-rest/build/samplerest/reports/profile/profile-2019-11-18-04-51-10.html
     [exec] Project directory '/opt/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates-rest/build/samplerest' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 
     [exec] A fine-grained performance profile is available: use the --scan option.* Try:
     [exec] 
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.InvalidUserDataException: Project directory '/opt/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates-rest/build/samplerest' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 	at org.gradle.initialization.AbstractProjectSpec.selectProject(AbstractProjectSpec.java:42)
     [exec] 	at org.gradle.initialization.DefaultSettingsLoader.setDefaultProject(DefaultSettingsLoader.java:88)
     [exec] 	at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:52)
     [exec] 	at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
```

**Unsure if related:**
Error on `yarnInstallPrivate` task

- CalendarCreateEvent#AddAllDay
- CalendarStaging#SchedulePublishToLiveWithEventAndResource
- SearchTuning#SearchWithSynonyms

```
   [exec] gyp verb `which` succeeded for `make` /usr/bin/make
     [exec] gyp info spawn make
     [exec] gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
     [exec] make: Entering directory `/opt/dev/projects/github/liferay-portal/modules/private/node_modules/node-sass/build'
     [exec]   g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.4"' -I/root/.node-gyp/10.15.1/include/node -I/root/.node-gyp/10.15.1/src -I/root/.node-gyp/10.15.1/deps/openssl/config -I/root/.node-gyp/10.15.1/deps/openssl/openssl/include -I/root/.node-gyp/10.15.1/deps/uv/include -I/root/.node-gyp/10.15.1/deps/zlib -I/root/.node-gyp/10.15.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++1y -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
     [exec] make: g++: Command not found
     [exec] make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
     [exec] make: Leaving directory `/opt/dev/projects/github/liferay-portal/modules/private/node_modules/node-sass/build'
     [exec] gyp ERR! build error 
     [exec] gyp ERR! stack Error: `make` failed with exit code: 2
     [exec] gyp ERR! stack     at ChildProcess.onExit (/opt/dev/projects/github/liferay-portal/modules/private/node_modules/node-gyp/lib/build.js:262:23)
     [exec] gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
     [exec] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
     [exec] gyp ERR! System Linux 4.14.138-rancher
     [exec] gyp ERR! command "/opt/dev/projects/github/liferay-portal/build/node/bin/node" "/opt/dev/projects/github/liferay-portal/modules/private/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
     [exec] gyp ERR! cwd /opt/dev/projects/github/liferay-portal/modules/private/node_modules/node-sass
     [exec] gyp ERR! node -v v10.15.1
     [exec] gyp ERR! node-gyp -v v3.8.0
     [exec] gyp ERR! not ok 
     [exec] Build failed with error code: 1
     [exec] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
     [exec] 
     [exec] > Task :yarnInstallPrivate FAILED
```

**Likely fluke:**

- PGSharepoint#ViewDocumentAsGuest

Comparison:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=882422603&testrayRunIdA=882673332&statusB=2

**Comment by petershin** [comment]
@lawrence-lee - Are the `project-templates` failures are due to the `7.3` update?

@john-co - The `yarnInstallPrivate` failure seems like a fluke.  I'll take a closer look.

**Comment by petershin** [comment]
@jbalsas - does the `yarn install` failure look familiar to you?

```
> Task :yarnInstall
Installing the Node.js packages
...
Using registry http://mirrors.lax.liferay.com:4873
yarn install v1.13.0
...
[4/4] Building fresh packages...
error /opt/dev/projects/github/liferay-portal/modules/private/node_modules/node-sass: Command failed.
Exit code: 1
...
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.4"' -I/root/.node-gyp/10.15.1/include/node -I/root/.node-gyp/10.15.1/src -I/root/.node-gyp/10.15.1/deps/openssl/config -I/root/.node-gyp/10.15.1/deps/openssl/openssl/include -I/root/.node-gyp/10.15.1/deps/uv/include -I/root/.node-gyp/10.15.1/deps/zlib -I/root/.node-gyp/10.15.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++1y -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
make: g++: Command not found
```

**Comment by lawrence-lee** [comment]
@petershin @john-co , We can ignore those functional tests in the `default` run.

**Comment by petershin** [comment]
Waiting for Greg to fix the `gradle-plugins-workspace` tests

Peter Yoo added a fix for the `yarn install` issue: [LRCI-494](https://issues.liferay.com/browse/LRCI-494)

**Comment by jbalsas** [comment]
Hey @petershin, not sure about the error, but that usually happens when the target platform does not have the proper libsass bindings and npm tries to compile them locally.

Not sure where this is running, so it's hard to know more...

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by petershin** [comment]
Rebased w the latest: https://github.com/petershin/liferay-portal/pull/798

**Pull request closed without merging**
