### PR TITLE
LPS-99983 translate jsp.precompile.enabled workspace property to use new compile.jsp.include on modules

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
@petershin  This failing test looks like internet related failure.

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/77760

**Pull request closed without merging**
