### PR TITLE
LCD-14296 CET Annotations

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Peter,

I made some changes.

1. Sort CETs: Before making any changes, when I run SF the json file will be changed(cets order), so I added logic to sort cets before generating json.

2. Without my changs f602c45c6ce05e60d53ad2430ac3116b476ee7b5, 
for example:
if we just change only one of CET*.java, the generated json will contain only that one CET.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by petershin** [comment]
Sending to bchan: https://github.com/petershin/liferay-portal/pull/1692

**Comment by ling-alan-huang** [comment]
Great!

**Pull request closed without merging**
