### PR TITLE
LPS-161876 Add lang-sanitizer tool support

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @petershin , since this [pull request](https://github.com/brianchandotcom/liferay-portal/pull/128060) desn't merged for more than two weeks, it seems github UI can not rebase it, I sent a new pr here to rebase it manually. Can you help rebase it on Brain's brach? Thanks a lot!

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@Seiphon @petershin weird, has [that init.jsp file](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-taglib/src/main/resources/META-INF/resources/init.jsp) been failing SF when it was last changed a month ago?  Or was a new rule introduced recently?

**Comment by Seiphon** [comment]
> @Seiphon @petershin weird, has [that init.jsp file](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-taglib/src/main/resources/META-INF/resources/init.jsp) [commit](https://github.com/liferay/liferay-portal/commit/2ff3add69544aac025034083fe147f42985be358) been failing SF when it was last changed a month ago? Or was a new rule introduced recently?

Let me confirm it with @ling-alan-huang , it's really weird

**Comment by ling-alan-huang** [comment]
SF failures are not related to this PR.
I sent the SF fix here: https://github.com/brianchandotcom/liferay-portal/pull/128445

**Comment by ling-alan-huang** [comment]
This PR will invoke `ant format-source-all` because your changes touched `source-formatter.properties`.

**Comment by Seiphon** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by Seiphon** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@Seiphon does this pull contain https://github.com/brianchandotcom/liferay-portal/commit/3d8de879ab0c605cafe13fcdc4050ae9ca9a7dfa?

@petershin If the changes look good, ci stable is passing, and SF is failing on a separate issue, can we just manually forward this to BChan?

**Comment by Seiphon** [comment]
> @Seiphon does this pull contain [brianchandotcom@3d8de87](https://github.com/brianchandotcom/liferay-portal/commit/3d8de879ab0c605cafe13fcdc4050ae9ca9a7dfa)?
> 
I rebased this pr to master this morning, it seems not contain the commit you mentiond

**Comment by petershin** [comment]
@brianwulbern - I've reviewed the [code earlier](https://github.com/brianchandotcom/liferay-portal/pull/128060), so this can be manually sent to bchan.

I'll manually fwd it when I return from pto on the 17th. If this is needed before then, feel free to send it directly to bchan and link it to the earlier pull in his queue.

**Comment by Seiphon** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
SF failures are not related to this PR.
The fixes are already sent here:
https://github.com/ling-alan-huang/liferay-portal/pull/1599
https://github.com/liferay-objects/liferay-portal/pull/1616

`ci:test:sf` will give the frequent failues becase ci will check all files when PR touches SF code.
 
@brianwulbern As Peter said, if this is an ungent PR, please send it directly to BChan.

**Comment by Seiphon** [comment]
> SF failures are not related to this PR. The fixes are already sent here: [ling-alan-huang#1599](https://github.com/ling-alan-huang/liferay-portal/pull/1599) [liferay-objects#1616](https://github.com/liferay-objects/liferay-portal/pull/1616)
> 
> `ci:test:sf` will give the frequent failues because SF will check all files when PR touches SF code.
> 
> @brianwulbern As Peter said, if this is an ungent PR, please send it directly to BChan.

I resent this pr manually to Bchan here https://github.com/brianchandotcom/liferay-portal/pull/128722

**Pull request closed without merging**
