### PR TITLE
LPS-91967 Yarn

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:bundle

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
Hi @john-co, do any of the failures look like they're caused by the changes in this pull?

**Comment by john-co** [comment]
Started reviewing :)

**Comment by john-co** [comment]
There are some unique failures that look related to the pull:
1. Filter and Order language key is missing from Management Toolbar
Selection_082

2. Search result for management toolbar has language key missing
Selection_083

3. Error was thrown when creating an instance
```
LIFERAY_ERROR: java.lang.RuntimeException: org.elasticsearch.index.engine.VersionConflictEngineException: [workflow-metrics-processes/GlynlEdHQA-_FHI9mO8yug][[workflow-metrics-processes][0]] VersionConflictEngineException[[WorkflowMetricsProcessType][WorkflowMetricsProcess_PORTLET_36348143b91eba69e744ae495df1914f89cb7be24ddf7c8cb99c5570113a6a0e]: version conflict, current version [2] is different than the one provided [1]]
```
Fails on: https://testray.liferay.com/home/-/testray/case_results/727664056
Log output: https://testray.liferay.com/reports/production/logs/test-1-22/1565709571168/test-portal-acceptance-pullrequest(master)/4688/functional-tomcat90-mysql57-jdk8/45/0/jenkins-console.txt.gz

Error looks similar to: https://issues.liferay.com/browse/LPS-98854

**Comment by petershin** [comment]
Thank you @john-co. Taking a look at the errors.

**Comment by petershin** [comment]
Sent a new pull: https://github.com/petershin/liferay-portal/pull/653

**Comment by petershin** [comment]
The `gradle-plugins-soy` plugin can't be removed because its enabled in a few projects.  Discussing with Chema the level of effort of moving away from those tasks

**Pull request closed without merging**
