### PR TITLE
LPS-114882 Add gradleTest for providedModules configuration in Target Platform

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
hey @petershin   these test failures seem unrelated to this change.

**Comment by petershin** [comment]
Forwarding to Brian: https://github.com/petershin/liferay-portal/pull/1035

**Pull request closed without merging**
