### PR TITLE
LPS-92634 Update operation ids

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by petershin** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
Hi @petershin, there are two non-flaky integration tests failing

- [ProcessVersionResourceTest.testGraphQLGetProcessProcessVersionsPage](https://testray.liferay.com/home/-/testray/case_results/1552438561?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1552436025%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
- [ReindexStatusResourceTest.testGraphQLGetReindexStatusesPage](https://testray.liferay.com/home/-/testray/case_results/1552438563?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1552436025%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

There is a functional test failing too, but I think that when integration tests will passed it will passed too

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Pull request closed without merging**
