### PR TITLE
LPS-103170

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Hey @petershin I tried to move some of segments in to modules/dxp/apps, but I get this error:

brian@laptop ~/dev/projects/github/liferay-portal/modules/dxp/apps (LPS-103170)
$ gw clean
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'clean' not found in root project 'apps'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by petershin** [comment]
@brianchandotcom - It's working for me.  I also tested removing your last commit and it seemed fine.

I'm running some more tests to try and reproduce the issue.

**Comment by petershin** [comment]
@brianchandotcom - I see it now.  Working on a fix

**Comment by petershin** [comment]
@brianchandotcom - Sorry for blocking you!  Sent a fix: https://github.com/brianchandotcom/liferay-portal/pull/79645

**Pull request closed without merging**
