### PR TITLE
LPS-173869 fix gradle plugin test Integration error

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
@petershin here is test result https://github.com/simonjhy/liferay-portal/pull/105

**Comment by petershin** [comment]
ci:test:stable

**Comment by petershin** [comment]
@simonjhy - Do the versions in the `testModules` configuration need to be changed?

If they do, did you test that its safe to backport to 7.0.x?

**Comment by petershin** [comment]
@simonjhy - Fwding everything except https://github.com/petershin/liferay-portal/pull/1897/commits/83f1186d820acc266a0d508faf04e3731831b6d0. See https://github.com/petershin/liferay-portal/pull/1899

If that change is needed, please run tests to check that its safe to backport to 7.0.x

**Comment by simonjhy** [comment]
@petershin yes, Thank you. I tested it  and it don't need to update testModules dependenies.

**Pull request closed without merging**
