### PR TITLE
LPS-86447 add environment support for BaseAppServerTask

### PR DESCRIPTION
**Pull request by gamerson**
@codyhoag

With this new feature, developers who want to start tomcat and make tomcat suspend until a debugger connects (to debug some portal startup issue) you can now do this:

```
startTestableTomcat {
    environment = ["JPDA_SUSPEND" : "y"]
    executableArgs = ["jpda", "run"]
 }
```

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test

**Comment by gamerson** [comment]
@petershin  Seems ok?

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/64288

**Pull request closed without merging**
